<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h1><?php _e('Playlists'); ?></h1>
    <?php if (isset($list) && !empty($list)) { ?>
        <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Can edit ?'); ?></th>
                <th><?php _e('Time'); ?></th>
                <th><?php _e('Hits'); ?></th>
                <th><?php _e('Price'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $playlist) { ?>
                <?php if ($playlist['status'] == 1) {
                    $badgeIdClass = 'badge-success';
                } elseif ($playlist['status'] == 5) {
                    $badgeIdClass = 'badge-danger';
                } else {
                    $badgeIdClass = 'badge-warning';
                } ?>
                <tr>
                    <td>
                        <span class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($playlist['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($playlist['title']); ?></td>
                    <td><?php echo $this->escape($playlist['can_edit']); ?></td>
                    <td><?php echo $this->escape($playlist['time_create_view']); ?></td>
                    <td><?php echo $this->escape($playlist['hits']); ?></td>
                    <td><?php echo $this->escape($playlist['sale_price_view']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $playlist['id']]); ?>">
                            <i class="fas fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger 3 mt-3" role="alert">
            <?php _e('Playlist is empty, perhaps you still didn\'t add any list or your selected filter didn\'t have any result'); ?>
        </div>
    <?php } ?>
</div>