<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h1><?php _e('List of servers'); ?></h1>
    <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Type'); ?></th>
            <th><?php _e('Address'); ?></th>
            <th><?php _e('Default'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $server) { ?>
            <?php
            if ($server['status'] == 1) {
                $badgeIdClass = 'badge-success';
            } elseif ($server['status'] == 5) {
                $badgeIdClass = 'badge-danger';
            } else {
                $badgeIdClass = 'badge-warning';
            }
            ?>
            <tr>
                <td>
                    <span class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($server['id']); ?></span>
                </td>
                <td><?php echo $this->escape($server['title']); ?></td>
                <td><?php echo $this->escape($server['type_view']); ?></td>
                <td>
                    <ul class="list-inline">
                        <li class="list-inline-item"><?php _e('Url') ?> : <?php echo $this->escape($server['url']); ?></li>
                        <?php if (!empty($server['application'])) { ?>
                            <li class="list-inline-item"><?php _e('Application') ?> : <?php echo $this->escape($server['application']); ?></li>
                        <?php } ?>
                    </ul>
                </td>
                <td>
                    <?php if ($server['default']) { ?>
                        <span class="badge badge-success"><?php _e('Yes'); ?></span>
                    <?php } else { ?>
                        <span class="badge badge-danger"><?php _e('No'); ?></span>
                    <?php } ?>
                </td>
                <td>
                    <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', ['action' => 'update', 'id' => $server['id']]); ?>">
                        <i class="fas fa-edit"></i> <?php _e('Edit'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>