<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add server'); ?>"
           href="<?php echo $this->url('', ['controller' => 'server', 'action' => 'update']); ?>"><i
                    class="fa fa-folder-open"></i> <?php _e('Add server'); ?></a>
    </p>

    <h3><?php _e('List of servers'); ?></h3>
    <table class="table table-striped table-bordered table-sm">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Type'); ?></th>
            <th><?php _e('Url'); ?></th>
            <th><?php _e('Default'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $server) { ?>
            <?php
            if ($server['status'] == 1) {
                $labelIdClass = 'label-success';
            } elseif ($server['status'] == 5) {
                $labelIdClass = 'label-danger';
            } else {
                $labelIdClass = 'label-warning';
            }
            ?>
            <tr>
                <td>
                    <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($server['id']); ?></span>
                </td>
                <td><?php echo $this->escape($server['title']); ?></td>
                <td><?php echo $this->escape($server['type_view']); ?></td>
                <td><?php echo $this->escape($server['url']); ?></td>
                <td>
                    <?php if ($server['default']) { ?>
                        <span class="badge badge-success"><?php _e('Yes'); ?></span>
                    <?php } else { ?>
                        <span class="badge badge-danger"><?php _e('No'); ?></span>
                    <?php } ?>
                </td>
                <td>
                    <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', ['action' => 'update', 'id' => $server['id']]); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    <?php if ($server['type'] == 'qmery') { ?>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-wrench"></i> <?php _e('Update'); ?>
                            </button>
                            <div class="dropdown-menu" role="menu">
                                <a class="dropdown-item" title="<?php _e('From qmery server'); ?>"
                                   href="<?php echo $this->url(
                                       '', ['controller' => 'server', 'action' => 'processing', 'server' => $server['id'], 'type' => 'syncVideoList']
                                   ); ?>"><i
                                            class="fa fa-wrench"></i> <?php _e('From qmery server'); ?></a>
                                <a class="dropdown-item" title="<?php _e('Website videos'); ?>"
                                   href="<?php echo $this->url(
                                       '', ['controller' => 'server', 'action' => 'processing', 'server' => $server['id'], 'type' => 'syncVideoSingle']
                                   ); ?>"><i
                                            class="fa fa-wrench"></i> <?php _e('Website videos from qmery'); ?></a>
                            </div>
                        </div>
                    <?php } ?>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>