<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h1><?php _e('Server types'); ?></h1>
    <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Name'); ?></th>
        </tr>
        <?php foreach ($list as $server) { ?>
            <tr>
                <td><?php echo $this->escape($server['id']); ?></td>
                <td><?php echo $this->escape($server['title']); ?></td>
                <td><?php echo $this->escape($server['name']); ?></td>
            </tr>
        <?php } ?>
    </table>
</div>