<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add server'); ?>"
           href="<?php echo $this->url('', array('controller' => 'server', 'action' => 'update')); ?>"><i
                class="fa fa-folder-open"></i> <?php _e('Add server'); ?></a>
    </p>

    <h3><?php _e('List of servers'); ?></h3>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Type'); ?></th>
            <th><?php _e('Url'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $server) { ?>
            <?php
            if ($server['status'] == 1) {
                $labelIdClass = 'label-success';
            } else {
                $labelIdClass = 'label-warning';
            }
            ?>
            <tr>
                <td><span
                        class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($server['id']); ?></span>
                </td>
                <td><?php echo $this->escape($server['title']); ?></td>
                <td><?php echo $this->escape($server['type_view']); ?></td>
                <td><?php echo $this->escape($server['url']); ?></td>
                <td>
                    <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', array('action' => 'update', 'id' => $server['id'])); ?>"><i
                            class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>