<?php
$this->css($this->assetModule('css/admin.css'));
$this->jQuery();
$script = <<<'EOT'
window.setTimeout(function() {
    window.location.href = '%s';
}, 10000);
EOT;
$script = sprintf($script, $url);
$this->footScript()->appendScript($script);
$script2 = <<<'EOT'
    var count=10;
    var counter=setInterval(timer, 1000);
    function timer()
    {
        count=count-1;
        if (count <= 0)
        {
            clearInterval(counter);
            return;
        }
        document.getElementById("timer").innerHTML="%s " + count + " %s";
    }
EOT;
$script2 = sprintf($script2, __('Please wait for'), __('secs'));
$this->footScript()->appendScript($script2);
?>
<div class="clearfix">
    <div class="alert alert-warning text-center">
        <p><i class="fa fa-cog fa-spin fa-4x fa-fw"></i></p>
        <p><strong><?php _e('At processing request, please wait dont close this page.'); ?></strong><strong><span id="timer"></span></strong></p>
    </div>
</div>