<?php
$this->css($this->assetModule('css/admin.css'));
/* if ($video['server']['type'] == 'wowza') {
    $this->jQuery();
    $this->js($this->assetModule('player/shaka/shaka-player.compiled.js'));
    $script
            = <<<'EOT'
    var manifestUri = '%s';

    function initApp() {
        // Install built-in polyfills to patch browser incompatibilities.
        shaka.polyfill.installAll();

        // Check to see if the browser supports the basic APIs Shaka needs.
        if (shaka.Player.isBrowserSupported()) {
            // Everything looks good!
            initPlayer();
        } else {
            // This browser does not have the minimum set of APIs we need.
            console.error('Browser not supported!');
        }
    }

    function initPlayer() {
        // Create a Player instance.
        var video = document.getElementById('video');
        var player = new shaka.Player(video);

        // Attach player to the window to make it easy to access in the JS console.
        window.player = player;
        
        // Set config
        // player.configure({});

        // Listen for error events.
        player.addEventListener('error', onErrorEvent);

        // Try to load a manifest.
        // This is an asynchronous process.
        player.load(manifestUri).then(function() {
            // This runs if the asynchronous load is successful.
            console.log('The video has now been loaded!');
        }).catch(onError);  // onError is executed if the asynchronous load fails.
    }

    function onErrorEvent(event) {
        // Extract the shaka.util.Error object from the event.
        onError(event.detail);
    }

    function onError(error) {
        // Log the error.
        console.error('Error code', error.code, 'object', error);
    }

    document.addEventListener('DOMContentLoaded', initApp);
EOT;
    $script = sprintf($script, $video['mpegDashUrl']);
    $this->footScript()->appendScript($script);
} */
?>
<div class="clearfix">
    <ul class="nav nav-pills bg-light mb-3 p-3">
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'link') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'link', 'id' => $video['id']]); ?>"><?php _e('Manage video source'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'update') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><?php _e('Manage basic information'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'additional') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><?php _e('Manage additional information'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'view') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'watch', 'id' => $video['id']]); ?>"><?php _e('Watch submitted video'); ?></a>
        </li>
        <?php if ($video['status'] == 1) { ?>
            <li class="nav-item pull-right">
                <a class="nav-link" target="_blank" href="<?php echo $video['videoUrl']; ?>"><?php _e('View'); ?></a>
            </li>
        <?php } ?>
    </ul>
    <?php if ($video['status'] != 1) { ?>
        <div class="alert alert-danger">
            <?php _e('This video not published on user side'); ?>
        </div>
    <?php } ?>
    <div class="page-header">
        <h1><?php echo $this->escape($video['title']); ?></h1>
    </div>
    <div class="text-center video-player-box col-lg-8 col-md-8 offset-lg-2 offset-md-2">
        <?php /* if ($video['server']['type'] == 'wowza') { ?>
            <div class="clearfix">
                <div id="videoContainer" class="overlay-parent">
                    <video id="video"
                           class="video-player"
                           width="100%"
                           poster="<?php echo $this->escape($videoItem['largeUrl']); ?>"
                           controls
                           autoplay></video>
                </div>
                <div class="card card-body bg-light mb-3 text-left">
                    <div class="form-group">
                        <label><?php _e('MPEG-Dash Url'); ?></label>
                        <input type="text" class="form-control"
                               value="<?php echo $this->escape($videoItem['mpegDashUrl']); ?>">
                    </div>
                    <div class="form-group">
                        <label><?php _e('Adobe Hds Url'); ?></label>
                        <input type="text" class="form-control"
                               value="<?php echo $this->escape($videoItem['adobeHdsUrl']); ?>">
                    </div>
                    <div class="form-group">
                        <label><?php _e('Jwplayer Url'); ?></label>
                        <input type="text" class="form-control"
                               value="<?php echo $this->escape($videoItem['jwplayerUrl']); ?>">
                    </div>
                    <div class="form-group">
                        <label><?php _e('IOS Url'); ?></label>
                        <input type="text" class="form-control"
                               value="<?php echo $this->escape($videoItem['iosUrl']); ?>">
                    </div>
                    <div class="form-group">
                        <label><?php _e('Android Url'); ?></label>
                        <input type="text" class="form-control"
                               value="<?php echo $this->escape($videoItem['androidUrl']); ?>">
                    </div>
                    <div class="form-group">
                        <label><?php _e('RTSP Url'); ?></label>
                        <input type="text" class="form-control"
                               value="<?php echo $this->escape($videoItem['rtspUrl']); ?>">
                    </div>
                    <div class="form-group">
                        <label><?php _e('RTMP Url'); ?></label>
                        <input type="text" class="form-control"
                               value="<?php echo $this->escape($videoItem['rtmpUrl']); ?>">
                    </div>
                </div>
            </div>
        <?php } */ ?>
        <?php if (!empty($video['video_url'])) { ?>
        <div class="clearfix">
            <?php echo $this->video($video['player']); ?>
        </div>
        <?php } else { ?>
            <div class="alert alert-danger">
                <?php _e('No media attached to this row'); ?>
            </div>
        <?php } ?>
    </div>
</div>