<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="list-header">
        <h3><?php _e('Update video not finished'); ?></h3>
    </div>
    <div class="alert alert-danger" role="alert">
        <?php echo $this->escape($message); ?>
    </div>
    <div class="clearfix">
        <div class="col-md-4 col-md-offset-4">
            <div class="btn-group d-flex">
                <a class="btn btn-primary" href="<?php echo Pi::url($this->url('', [
                    'action' => 'qmeryUpdate',
                    'id'     => $video['id'],
                ])); ?>">
                    <?php _e('Retry again !'); ?>
                </a>
            </div>
        </div>
    </div>
</div>