<?php
$this->css($this->assetModule('css/admin.css'));
if ($config['broadcast_system'] == 'wowza') {
    $this->jQuery();
    $this->js($this->assetModule('player/shaka/shaka-player.compiled.js'));
    $this->js($this->assetModule('player/shaka/controls.js'));
    $this->css($this->assetModule('player/shaka/controls.css'));
    $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Roboto');
    $this->headLink()->appendStylesheet('https://fonts.googleapis.com/css?family=Roboto+Condensed');
    $this->headLink()->appendStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons');
    $script = <<<'EOT'
    var manifestUri = '%s';

    function initApp() {
        // Install built-in polyfills to patch browser incompatibilities.
        shaka.polyfill.installAll();

        // Check to see if the browser supports the basic APIs Shaka needs.
        if (shaka.Player.isBrowserSupported()) {
            // Everything looks good!
            initPlayer();
        } else {
            // This browser does not have the minimum set of APIs we need.
            console.error('Browser not supported!');
        }
    }

    function initPlayer() {
        // Create a Player instance.
        var video = document.getElementById('video');
        var player = new shaka.Player(video);

        // Attach player to the window to make it easy to access in the JS console.
        window.player = player;

        // Listen for error events.
        player.addEventListener('error', onErrorEvent);

        // Try to load a manifest.
        // This is an asynchronous process.
        player.load(manifestUri).then(function() {
            // This runs if the asynchronous load is successful.
            console.log('The video has now been loaded!');
        }).catch(onError);  // onError is executed if the asynchronous load fails.
    }

    function onErrorEvent(event) {
        // Extract the shaka.util.Error object from the event.
        onError(event.detail);
    }

    function onError(error) {
        // Log the error.
        console.error('Error code', error.code, 'object', error);
    }

    document.addEventListener('DOMContentLoaded', initApp);
EOT;
    $script = sprintf($script, $video['mpegDashUrl']);
    $this->footScript()->appendScript($script);
}
?>
<div class="clearfix">
    <div class="well well-sm">
        <ul class="nav nav-pills nav-justified">
            <li<?php if ($nav['page'] == 'link') { echo ' class="active"';} ?>><a href="<?php echo $this->url('', array('action' => 'link', 'id' => $video['id'])); ?>"><?php _e('Manage video link'); ?></a></li>
            <li<?php if ($nav['page'] == 'update') { echo ' class="active"';} ?>><a href="<?php echo $this->url('', array('action' => 'update', 'id' => $video['id'])); ?>"><?php _e('Edit basic information'); ?></a></li>
            <li<?php if ($nav['page'] == 'additional') { echo ' class="active"';} ?>><a href="<?php echo $this->url('', array('action' => 'additional', 'id' => $video['id'])); ?>"><?php _e('Edit additional information'); ?></a></li>
            <li<?php if ($nav['page'] == 'view') { echo ' class="active"';} ?>><a href="<?php echo $this->url('', array('action' => 'view', 'id' => $video['id'])); ?>"><?php _e('Watch submitted video'); ?></a></li>
            <?php if ($video['status'] == 1) { ?>
                <li class="active pull-right"><a target="_blank" href="<?php echo $video['videoUrl']; ?>"><?php _e('View'); ?></a></li>
            <?php } ?>
        </ul>
    </div>
    <?php if ($video['status'] != 1) { ?>
        <div class="alert alert-danger">
            <?php _e('This video not published on user side'); ?>
        </div>
    <?php } ?>
    <div class="page-header">
        <h1><?php echo $this->escape($video['title']); ?></h1>
    </div>
    <div class="text-center video-player-box col-md-8 col-md-offset-2">
        <?php if ($config['broadcast_system'] == 'file') { ?>
            <?php echo $this->videojs($video['videoFileUrl'], $video['largeUrl']); ?>
        <?php } elseif ($config['broadcast_system'] == 'wowza') { ?>
            <div class="clearfix">
                <div id="videoContainer" class="overlay-parent">
                    <video id="video"
                           poster="<?php echo $this->escape($video['largeUrl']); ?>"
                           controls></video>
                    <!-- <div id="giantPlayButtonContainer" class="overlay">
                        <button id="giantPlayButton" class="material-icons">play_arrow</button>
                    </div>
                    <div id="bufferingSpinner" class="overlay">
                        <svg class="spinnerSvg" viewBox="25 25 50 50">
                            <circle class="spinnerPath" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
                        </svg>
                    </div>
                    <div id="castReceiverName" class="overlay"></div>
                    <div id="controlsContainer" class="overlay">
                        <div id="controls">
                            <button id="playPauseButton" class="material-icons">play_arrow</button>
                            <input id="seekBar" type="range" step="any" min="0" max="1" value="0">
                            <button id="rewindButton" class="material-icons">fast_rewind</button>
                            <div id="currentTime">0:00</div>
                            <button id="fastForwardButton" class="material-icons">fast_forward</button>
                            <button id="muteButton" class="material-icons">volume_up</button>
                            <input id="volumeBar" type="range" step="any" min="0" max="1" value="0">
                            <button id="castButton" class="material-icons">cast</button>
                            <button id="captionButton" class="material-icons">closed_caption</button>
                            <button id="fullscreenButton" class="material-icons">fullscreen</button>
                        </div>
                    </div> -->
                </div>
            </div>
        <?php } ?>
    </div>
</div>