<?php
$this->css($this->assetModule('css/admin.css'));
$this->jQuery();

// Set page script
if (!isset($video['id']) && count($serverList) > 1) {
    $script = <<<'EOT'
    (function ($) {
        $(document).ready(function ($) {
            $('div[data-name="video_path"]').hide();
            $('div[data-name="video_file"]').hide();
            $('div[data-name="show_video_url"]').hide();
            $('div[data-name="video_url"]').hide();
            $('input[name="video_path"]').prop('required',true);
            $('input[name="video_file"]').prop('required',true);
            $('input[name="video_url"]').prop('required',false);

            $('.video-server').change(function () {
                $('input[name="video_path"]:text').val('');
                $('input[name="video_file"]:text').val('');
                $('input[name="video_url"]:text').val('');
                $('div[data-name="video_path"]').show();
                $('div[data-name="video_file"]').show();
                $('div[data-name="show_video_url"]').show();
                $('.show-video-url').prop('checked', false);
                $('div[data-name="video_url"]').hide();
            });

            $('.show-video-url').change(function () {
                if(this.checked) {
                    $('div[data-name="video_url"]').show();
                    $('div[data-name="video_path"]').hide();
                    $('div[data-name="video_file"]').hide();
                    $('input[name="video_path"]:text').val('');
                    $('input[name="video_file"]:text').val('');
                    $('input[name="video_path"]').prop('required',false);
                    $('input[name="video_file"]').prop('required',false);
                    $('input[name="video_url"]').prop('required',true);
                } else {
                    $('div[data-name="video_url"]').hide();
                    $('div[data-name="video_path"]').show();
                    $('div[data-name="video_file"]').show();
                    $('input[name="video_url"]:text').val('');
                    $('input[name="video_path"]').prop('required',true);
                    $('input[name="video_file"]').prop('required',true);
                    $('input[name="video_url"]').prop('required',false);
                }
            });
        });
    })(jQuery)
EOT;
    $this->footScript()->appendScript($script);
}
?>
<div class="clearfix">
    <ul class="nav nav-pills bg-light mb-3 p-3">
        <?php if (isset($video['id'])) { ?>
            <li class="nav-item">
                <a class="nav-link <?php if ($nav['page'] == 'link') {
                    echo 'active';
                } ?>" href="<?php echo $this->url('', ['action' => 'link', 'id' => $video['id']]); ?>"><?php _e('Manage video source'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?php if ($nav['page'] == 'update') {
                    echo 'active';
                } ?>" href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><?php _e('Manage basic information'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?php if ($nav['page'] == 'additional') {
                    echo 'active';
                } ?>" href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><?php _e('Manage additional information'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?php if ($nav['page'] == 'view') {
                    echo 'active';
                } ?>" href="<?php echo $this->url('', ['action' => 'watch', 'id' => $video['id']]); ?>"><?php _e('Watch submitted video'); ?></a>
            </li>
            <?php if ($video['status'] == 1) { ?>
                <li class="nav-item pull-right">
                    <a class="nav-link" target="_blank" href="<?php echo $video['videoUrl']; ?>"><?php _e('View'); ?></a>
                </li>
            <?php } ?>
        <?php } else { ?>
            <li class="nav-item">
                <a class="nav-link active" href="#"><?php _e('Add video source'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><?php _e('Manage basic information'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><?php _e('Manage additional information'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><?php _e('Watch submitted video'); ?></a>
            </li>
        <?php } ?>
    </ul>
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php echo $this->form($form); ?>
</div>