<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <ul class="nav nav-pills bg-light mb-3 p-3">
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'link') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'link', 'id' => $video['id']]); ?>"><?php _e('Manage video source'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'update') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><?php _e('Manage basic information'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'additional') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><?php _e('Manage additional information'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'view') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'watch', 'id' => $video['id']]); ?>"><?php _e('Watch submitted video'); ?></a>
        </li>
        <?php if ($video['status'] == 1) { ?>
            <li class="nav-item pull-right">
                <a class="nav-link" target="_blank" href="<?php echo $video['videoUrl']; ?>"><?php _e('View'); ?></a>
            </li>
        <?php } ?>
    </ul>
    <?php if ($video['status'] != 1) { ?>
        <div class="alert alert-danger">
            <?php _e('This video not published on user side'); ?>
        </div>
    <?php } ?>
    <div class="page-header">
        <h1><?php echo $this->escape($video['title']); ?></h1>
    </div>
    <div class="text-center video-player-box col-lg-8 col-md-8 offset-lg-2 offset-md-2">
        <?php if (!empty($video['video_url'])) { ?>
        <div class="clearfix">
            <?php if (in_array($video['player_type'], ['mp4', 'hls'])) { ?>
                <?php echo $this->video($video['player']); ?>
            <?php } elseif ($video['player_type'] === 'embed') { ?>
                <?php echo $video['player']; ?>
            <?php } ?>
        </div>
        <?php } else { ?>
            <div class="alert alert-danger">
                <?php _e('No media attached to this row'); ?>
            </div>
        <?php } ?>
    </div>
</div>