<?php
$this->css(
    [
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="clearfix">

    <div id="search-box">
        <div class="card">
            <div class="card-header" id="searchHeading">
                <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapseSearch" aria-expanded="true" aria-controls="collapseSearch">
                        <i class="fas fa-plus"></i> <?php _e('Filter videos'); ?>
                    </button>
                </h5>
            </div>
            <div id="collapseSearch" class="collapse" aria-labelledby="searchHeading" data-parent="#search-box">
                <div class="card-body">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix list-header mt-3">
        <h1><?php _e('List of videos'); ?></h1>
    </div>

    <?php if (!empty($list)) { ?>
        <table id="video-list" class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
            <tr>
                <th><?php _e('Id'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Server'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $video) { ?>
                <?php if ($video['status'] == 1) {
                    $badgeIdClass = 'badge-success';
                } elseif ($video['status'] == 5) {
                    $badgeIdClass = 'badge-danger';
                } else {
                    $badgeIdClass = 'badge-warning';
                } ?>
                <tr>
                    <td>
                        <span class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($video['id']); ?></span>
                    </td>
                    <td class="video-ajax">
                        <?php if ($video['recommended'] == 1) { ?>
                            <button id="button-<?php echo $video['id']; ?>" type="button" class="btn btn-link"
                                    data-toggle="button"
                                    data-link="<?php echo $this->url('', ['action' => 'recommend', 'id' => $video['id'], 'recommended' => '0']); ?>">
                                <i class="fas fa-heart"></i></button>
                        <?php } else { ?>
                            <button id="button-<?php echo $video['id']; ?>" type="button" class="btn btn-link"
                                    data-toggle="button"
                                    data-link="<?php echo $this->url('', ['action' => 'recommend', 'id' => $video['id'], 'recommended' => '1']); ?>">
                                <i class="far fa-heart"></i></button>
                        <?php } ?>
                        <?php echo $this->escape($video['title']); ?>
                        <?php if ($video['hits'] > 0) { ?> ( <?php _e('View'); ?> : <?php echo $this->escape(_number($video['hits'])); ?> )<?php } ?>
                    </td>
                    <td>
                        <?php echo $this->escape($video['server']['title']); ?> ( <small><?php echo $this->escape($video['server']['type']); ?></small> )
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                <i class="fas fa-edit"></i> <?php _e('Manage'); ?>
                            </button>
                            <div class="dropdown-menu" role="menu">
                                <a class="dropdown-item" title="<?php _e('Manage video link'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'link', 'id' => $video['id']]); ?>"><i
                                            class="fas fa-edit"></i> <?php _e('Manage video link'); ?></a>
                                <a class="dropdown-item" title="<?php _e('Edit basic information'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><i
                                            class="fas fa-edit"></i> <?php _e('Edit basic information'); ?></a>
                                <a class="dropdown-item" title="<?php _e('Edit additional information'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><i
                                            class="fas fa-edit"></i> <?php _e('Edit additional information'); ?></a>

                                <a class="dropdown-item" title="<?php _e('View video'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'watch', 'id' => $video['id']]); ?>"><i
                                            class="fas fa-edit"></i> <?php _e('View video'); ?></a>
                            </div>
                        </div>
                        <?php if ($video['status'] == 1) { ?>
                            <a class="btn btn-success btn-sm" title="<?php _e('View'); ?>"
                               href="<?php echo $video['videoUrl']; ?>" target="_blank"><i
                                        class="fas fa-eye"></i> <?php _e('View'); ?></a>
                        <?php } ?>
                        <?php if ($video['status'] != 5) { ?>
                            <a class="btn btn-danger btn-sm" title="<?php _e('Delete'); ?>"
                               href="<?php echo $this->url('', ['action' => 'delete', 'id' => $video['id']]); ?>"
                               onclick="return confirm('<?php echo _a('Are you sure to delete this video?'); ?>')">
                                <i class="fas fa-trash"></i> <?php _e('Delete'); ?>
                            </a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
        <p>
            <span class="badge badge-success"><?php _e('Published'); ?></span>
            <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
            <span class="badge badge-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-danger 3 mt-3" role="alert">
            <?php _e('Product list is empty, perhaps you still didn\'t add any product or your selected filter didn\'t have any result'); ?>
        </div>
    <?php } ?>
</div>
<script type="text/javascript">
    (function ($) {
        $("#video-list .video-ajax").on("click", "button", function () {
            systemMessage.wait("<?php _e('Recommended in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.ajaxstatus == 1) {
                    if (result.recommended == 1) {
                        var buttonClass = 'fas fa-heart';
                    }
                    if (result.recommended == 0) {
                        var buttonClass = 'far fa-heart';
                    }
                    $('#button-' + result.id + ' i').attr('class', buttonClass);
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>