<?php
$this->jquery();
$this->css($this->assetModule('css/admin.css'));
$this->js(array(
    $this->assetModule('js/jquery.form.js'),
    $this->assetModule('js/progress-bar.js'),
));
$script = <<<'EOT'
    $('#videoFile').on('change', function (e) {
        var file = this.files[0];
        var fileSize = (file.size / 1000000).toFixed(2);
        var fileExtension = file.name.split('.').pop().toLowerCase();
        $('.fileInformation').removeClass('hidden');
        $('.fileInformationSize').text("%s " + fileSize + " MB " + " %s " + fileExtension);
        if (file.size > %s) {
            $('.fileInformationSizeError').removeClass('hidden');
            $('.fileInformationSizeError').text("%s");
            var fileSizeOk = 0;
            e.preventDefault();
        } else {
            $('.fileInformationSizeError').addClass('hidden');
            $('.fileInformationSizeError').text(' ');
            var fileSizeOk = 1;
            e.preventDefault();
        }
        if($.inArray(fileExtension, ['mp3','mp4']) == -1) {
            $('.fileInformationExtensionError').removeClass('hidden');
            $('.fileInformationExtensionError').text("%s");
            var fileExtensionOk = 0;
            e.preventDefault();
        } else {
            $('.fileInformationExtensionError').addClass('hidden');
            $('.fileInformationExtensionError').text(' ');
            var fileExtensionOk = 1;
            e.preventDefault();
        }
        if (fileSizeOk  == 1 && fileExtensionOk == 1) {
            $('.videoUpload').removeAttr("disabled");
        } else {
           $('.videoUpload').attr('disabled', true);
        }
    });
EOT;
$fileSize = __('Your selected file size is');
$fileExtension  = __('And file extension is');
$fileSizeError = sprintf(__('You attach to large file, allowed upload size is %s'), number_format($config['media_size'] / 1000000, 2) . ' MB');
$fileExtensionError  = sprintf(__('You attach wrong file, allowed extensions is %s'), $config['media_extension']);
$script = sprintf($script, $fileSize, $fileExtension, $config['media_size'], $fileSizeError, $fileExtensionError);
$this->footScript()->appendScript($script);
?>
<div class="clearfix">
    <div class="well well-sm">
        <ul class="nav nav-pills nav-justified">
            <li class="active"><a href="<?php echo $this->url('', array('action' => 'upload')); ?>"><?php _e('Upload video'); ?></a></li>
            <li><a href="#"><?php _e('Add basic information'); ?></a></li>
            <li><a href="#"><?php _e('Add additional information'); ?></a></li>
            <li><a href="#"><?php _e('Watch submitted video'); ?></a></li>
        </ul>
    </div>
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div class="alert alert-info">
        <?php echo sprintf(__('You just allow upload media with <strong>%s</strong> extensions, maximum upload size is <strong>%s</strong>'), $config['media_extension'], number_format($config['media_size'] / 1000000, 2) . ' MB') ?>
    </div>
    <div class="well well-sm">
        <div class="fileInformation hidden">
            <div class="fileInformationSize text-success"></div>
            <div class="fileInformationSizeError text-danger hidden"></div>
            <div class="fileInformationExtensionError text-danger hidden"></div>
        </div>
        <?php echo $this->form($form, 'inline'); ?>
    </div>
    <div id="progress-bar" class="progress">
        <div id="bar" class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            <div id="percent">0%</div>
        </div>
    </div>
</div>