<div class="clearfix">
    <ul class="nav nav-pills bg-light mb-3 p-3">
        <?php if (isset($video['id'])) { ?>
            <li class="nav-item">
                <a class="nav-link <?php if ($nav['page'] == 'link') {
                    echo 'active';
                } ?>" href="<?php echo $this->url('', ['action' => 'link', 'id' => $video['id']]); ?>"><?php _e('Manage video source'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?php if ($nav['page'] == 'update') {
                    echo 'active';
                } ?>" href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><?php _e('Manage basic information'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?php if ($nav['page'] == 'additional') {
                    echo 'active';
                } ?>" href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><?php _e('Manage additional information'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link <?php if ($nav['page'] == 'view') {
                    echo 'active';
                } ?>" href="<?php echo $this->url('', ['action' => 'watch', 'id' => $video['id']]); ?>"><?php _e('Watch submitted video'); ?></a>
            </li>
            <?php if ($video['status'] == 1) { ?>
                <li class="nav-item pull-right">
                    <a class="nav-link" target="_blank" href="<?php echo $video['videoUrl']; ?>"><?php _e('View'); ?></a>
                </li>
            <?php } ?>
        <?php } else { ?>
            <li class="nav-item">
                <a class="nav-link active" href="#"><?php _e('Add video source'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><?php _e('Manage basic information'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><?php _e('Manage additional information'); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><?php _e('Watch submitted video'); ?></a>
            </li>
        <?php } ?>
    </ul>
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php echo $this->form($form); ?>
</div>