<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="video-form" class="clearfix">
    <div class="well well-sm">
        <ul class="nav nav-pills">
            <li<?php if ($nav['page'] == 'link') { echo ' class="active"';} ?>><a href="<?php echo $this->url('', array('action' => 'link', 'id' => $video['id'])); ?>"><?php _e('Manage video link'); ?></a></li>
            <li<?php if ($nav['page'] == 'update') { echo ' class="active"';} ?>><a href="<?php echo $this->url('', array('action' => 'update', 'id' => $video['id'])); ?>"><?php _e('Edit basic information'); ?></a></li>
            <li<?php if ($nav['page'] == 'additional') { echo ' class="active"';} ?>><a href="<?php echo $this->url('', array('action' => 'additional', 'id' => $video['id'])); ?>"><?php _e('Edit additional information'); ?></a></li>
            <li<?php if ($nav['page'] == 'view') { echo ' class="active"';} ?>><a href="<?php echo $this->url('', array('action' => 'watch', 'id' => $video['id'])); ?>"><?php _e('Watch submitted video'); ?></a></li>
            <?php if ($video['status'] == 1) { ?>
                <li class="active pull-right"><a target="_blank" href="<?php echo $video['videoUrl']; ?>"><?php _e('View'); ?></a></li>
            <?php } ?>
        </ul>
    </div>
    <?php echo $this->form($form); ?>
</div>
<script type="text/javascript">
(function($){
    $(".video-from-status").parent(".js-form-element").parent(".form-group").addClass("bg-primary").css("padding", "15px");
    $("#video-form").on("click","button",function(){
       systemMessage.wait("<?php _e('Remove image video in process'); ?>");
       $.getJSON($(this).attr("data-link")).done(function(result){
          if(result.status==1){
             systemMessage.succ(result.message);
          }else{
             systemMessage.fail(result.message);
          }
       });
    });
})(jQuery)
</script>