<div class="clearfix">
    <div class="well well-sm">
        <ul class="nav nav-pills">
            <?php if (isset($video['id'])) { ?>
                <li<?php if ($nav['page'] == 'link') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['action' => 'link', 'id' => $video['id']]); ?>"><?php _e('Manage video link'); ?></a>
                </li>
                <li<?php if ($nav['page'] == 'update') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><?php _e('Edit basic information'); ?></a>
                </li>
                <li<?php if ($nav['page'] == 'additional') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><?php _e('Edit additional information'); ?></a>
                </li>
                <li<?php if ($nav['page'] == 'view') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['action' => 'watch', 'id' => $video['id']]); ?>"><?php _e('Watch submitted video'); ?></a>
                </li>
                <?php if ($video['status'] == 1) { ?>
                    <li class="active pull-right"><a target="_blank"
                                                     href="<?php echo $video['videoUrl']; ?>"><?php _e('View'); ?></a>
                    </li>
                <?php } ?>
            <?php } else { ?>
                <li class="active"><a
                            href="<?php echo $this->url('', ['action' => 'link']); ?>"><?php _e('Manage video link'); ?></a>
                </li>
                <li class="disabled"><a href="#"><?php _e('Add basic information'); ?></a></li>
                <li class="disabled"><a href="#"><?php _e('Add additional information'); ?></a></li>
                <li class="disabled"><a href="#"><?php _e('Watch submitted video'); ?></a></li>
            <?php } ?>
        </ul>
    </div>
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php echo $this->form($form); ?>
</div>