<?php
$this->css(
    [
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="clearfix">
    <div class="card-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="card card-body bg-light mb-3">
            <div class="card-heading" role="tab" id="headingForm">
                <h4 class="card-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion"
                       href="#collapseForm" aria-expanded="false" aria-controls="collapseForm">
                        <i class="fa fa-plus"></i> <?php _e('Filter videos'); ?>
                    </a>
                </h4>
            </div>
            <div id="collapseForm" class="card-collapse collapse" role="tabpanel" aria-labelledby="headingForm">
                <div class="card-text">
                    <?php echo $this->form($form); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix row list-header">
        <div class="col-6">
            <h3><?php _e('List of videos'); ?></h3>
        </div>
        <div class="col-6 text-right">
            <div class="btn-group">
                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-folder-open"></i> <?php _e('Add video'); ?>
                </button>
                <ul class="dropdown-menu dropdown-menu-left" role="menu">
                    <?php foreach ($serverList as $server) { ?>
                        <?php if ($server['type'] == 'file') { ?>
                            <li><a title="<?php echo $this->escape($server['title']); ?>"
                                   href="<?php echo $this->url(
                                       '', [
                                       'controller' => 'video',
                                       'action'     => 'upload',
                                       'server'     => $server['id'],
                                   ]
                                   ); ?>"><i
                                            class="fa fa-file"></i> <?php echo $this->escape($server['title']); ?></a>
                            </li>
                        <?php } elseif ($server['type'] == 'wowza') { ?>
                            <li><a title="<?php echo $this->escape($server['title']); ?>"
                                   href="<?php echo $this->url(
                                       '', [
                                       'controller' => 'video',
                                       'action'     => 'link',
                                       'server'     => $server['id'],
                                   ]
                                   ); ?>"><i
                                            class="fa fa-file"></i> <?php echo $this->escape($server['title']); ?></a>
                            </li>
                        <?php } elseif ($server['type'] == 'qmery') { ?>
                            <li><a title="<?php echo $this->escape($server['title']); ?>"
                                   href="<?php echo $this->url(
                                       '', [
                                       'controller' => 'video',
                                       'action'     => 'upload',
                                       'server'     => $server['id'],
                                   ]
                                   ); ?>"><i
                                            class="fa fa-file"></i> <?php echo $this->escape($server['title']); ?>
                                    (<?php _e('Upload'); ?>)</a></li>
                            <li><a title="<?php echo $this->escape($server['title']); ?>"
                                   href="<?php echo $this->url(
                                       '', [
                                       'controller' => 'video',
                                       'action'     => 'link',
                                       'server'     => $server['id'],
                                   ]
                                   ); ?>"><i
                                            class="fa fa-file"></i> <?php echo $this->escape($server['title']); ?>
                                    (<?php _e('Internal link'); ?>)</a></li>
                            <li><a title="<?php echo $this->escape($server['title']); ?>"
                                   href="<?php echo $this->url(
                                       '', [
                                       'controller' => 'video',
                                       'action'     => 'external',
                                       'server'     => $server['id'],
                                   ]
                                   ); ?>"><i
                                            class="fa fa-file"></i> <?php echo $this->escape($server['title']); ?>
                                    (<?php _e('External link'); ?>)</a></li>
                            <li><a title="<?php _e('From qmery to website'); ?>"
                                   href="<?php echo $this->url(
                                       '', [
                                       'controller' => 'server',
                                       'action'     => 'processing',
                                       'server'     => $server['id'],
                                       'type'       => 'syncVideoList',
                                   ]
                                   ); ?>"><i class="fa fa-wrench"></i> <?php echo $this->escape($server['title']); ?>
                                    (<?php _e('From qmery to website'); ?>)</a></li>
                        <?php } ?>
                        <li role="separator" class="divider"></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>
    <?php if (!empty($list)) { ?>
        <table id="video-list" class="table table-striped table-bordered table-hover table-sm">
            <tr>
                <th class="col-lg-6 col-md-6"><?php _e('Title'); ?></th>
                <th class="col-lg-2 col-md-2"><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $video) { ?>
                <?php if ($video['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($video['status'] == 5) {
                    $labelIdClass = 'label-danger';
                } else {
                    $labelIdClass = 'label-warning';
                } ?>
                <tr>
                    <td class="video-ajax">
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($video['id']); ?></span>
                        <?php if ($video['recommended'] == 1) { ?>
                            <button id="button-<?php echo $video['id']; ?>" type="button" class="btn btn-link"
                                    data-toggle="button"
                                    data-link="<?php echo $this->url('', ['action' => 'recommend', 'id' => $video['id'], 'recommended' => '0']); ?>">
                                <i class="fa fa-heart"></i></button>
                        <?php } else { ?>
                            <button id="button-<?php echo $video['id']; ?>" type="button" class="btn btn-link"
                                    data-toggle="button"
                                    data-link="<?php echo $this->url('', ['action' => 'recommend', 'id' => $video['id'], 'recommended' => '1']); ?>">
                                <i class="fa fa-heart-o"></i></button>
                        <?php } ?>
                        <?php echo $this->escape($video['title']); ?>
                        ( <?php _e('Server'); ?> : <?php echo $this->escape($video['server']['title']); ?> )
                        <?php if ($video['hits'] > 0) { ?> ( <?php _e('View'); ?> : <?php echo $this->escape(_number($video['hits'])); ?> )<?php } ?>
                    </td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-edit"></i> <?php _e('Manage'); ?>
                            </button>
                            <div class="dropdown-menu" role="menu">
                                <a class="dropdown-item" title="<?php _e('Manage video link'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'link', 'id' => $video['id']]); ?>"><i
                                            class="fa fa-edit"></i> <?php _e('Manage video link'); ?></a>
                                <a class="dropdown-item" title="<?php _e('Edit basic information'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><i
                                            class="fa fa-edit"></i> <?php _e('Edit basic information'); ?></a>
                                <a class="dropdown-item" title="<?php _e('Edit additional information'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><i
                                            class="fa fa-edit"></i> <?php _e('Edit additional information'); ?></a>

                                <a class="dropdown-item" title="<?php _e('View video'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'watch', 'id' => $video['id']]); ?>"><i
                                            class="fa fa-edit"></i> <?php _e('View video'); ?></a>
                            </div>
                        </div>
                        <?php if ($video['status'] == 1) { ?>
                            <a class="btn btn-success btn-sm" title="<?php _e('View'); ?>"
                               href="<?php echo $video['videoUrl']; ?>" target="_blank"><i
                                        class="fa fa-eye"></i> <?php _e('View'); ?></a>
                        <?php } ?>
                        <?php if ($video['status'] != 5) { ?>
                            <a class="btn btn-danger btn-sm" title="<?php _e('Delete'); ?>"
                               href="<?php echo $this->url('', ['action' => 'delete', 'id' => $video['id']]); ?>"
                               onclick="return confirm('<?php echo _a('Are you sure to delete this video?'); ?>')">
                                <i class="fa fa-trash"></i> <?php _e('Delete'); ?>
                            </a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
        <p>
            <span class="badge badge-success"><?php _e('Published'); ?></span>
            <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
            <span class="badge badge-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('Product list is empty, perhaps you still didn\'t add any product or your selected filter didn\'t have any result'); ?>
        </div>
    <?php } ?>
</div>
<script type="text/javascript">
    (function ($) {
        $("#video-list .video-ajax").on("click", "button", function () {
            systemMessage.wait("<?php _e('Recommended in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.ajaxstatus == 1) {
                    if (result.recommended == 1) {
                        var buttonClass = 'fa fa-heart';
                    }
                    if (result.recommended == 0) {
                        var buttonClass = 'fa fa-heart-o';
                    }
                    $('#button-' + result.id + ' i').attr('class', buttonClass);
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>