<?php
$this->css(
    [
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="video-form" class="clearfix">
    <ul class="nav nav-pills bg-light mb-3 p-3">
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'link') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'link', 'id' => $video['id']]); ?>"><?php _e('Manage video source'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'update') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><?php _e('Manage basic information'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'additional') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><?php _e('Manage additional information'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?php if ($nav['page'] == 'view') {
                echo 'active';
            } ?>" href="<?php echo $this->url('', ['action' => 'watch', 'id' => $video['id']]); ?>"><?php _e('Watch submitted video'); ?></a>
        </li>
        <?php if ($video['status'] == 1) { ?>
            <li class="nav-item pull-right">
                <a class="nav-link" target="_blank" href="<?php echo $video['videoUrl']; ?>"><?php _e('View'); ?></a>
            </li>
        <?php } ?>
    </ul>
    <?php echo $this->form($form); ?>
</div>
<script type="text/javascript">
    (function ($) {
        $(".video-from-status").parent(".js-form-element").parent(".form-group").addClass("bg-primary").css("padding", "15px");
        $("#video-form").on("click", "button", function () {
            systemMessage.wait("<?php _e('Remove image video in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.status == 1) {
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>