<?php if ($block['resources']['server']['type'] == 'qmery') {
    $this->jQuery();
    $this->headScript()->appendFile($block['resources']['qmeryScriptResponsive']);
} ?>
<div class="video-block video-block-select">
    <div class="clearfix">
        <?php if ($block['resources']['server']['type'] == 'qmery') { ?>
            <div class="qmery-player-min-height">
                <div class="qmery-player-full-height">
                    <div class="qmery-player">
                        <div id="embed_qmery_player_<?php echo $this->escape($block['resources']['video_qmery_id']); ?>"></div>
                        <div id="embed_qmery_player_icons<?php echo $this->escape($block['resources']['video_qmery_id']); ?>"></div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>