<div class="video-block">
    <div class="clearfix">
        <?php if ($block['list-type'] == 'horizontal') { ?>
            <?php foreach ($block['resources'] as $video) { ?>
                <div class="col-sm-6 col-md-4 videoBox h-review" itemscope itemtype="http://schema.org/VideoObject">
                    <meta itemprop="thumbnail" content="<?php echo $this->escape($video['largeUrl']); ?>" />
                    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $video['time_publish'])); ?>" />
                    <meta itemprop="contentUrl" content="<?php echo $this->escape($video['videoFileUrl']); ?>" />
                    <div class="thumbnail">
                        <?php if ($video['image']) { ?>
                            <a itemprop="url" class="u-photo" title="<?php echo $this->escape($video['title']); ?>"
                               href="<?php echo $this->escape($video['videoUrl']); ?>">
                                <img itemprop="image" src="<?php echo $video['thumbUrl']; ?>"
                                     alt="<?php echo $this->escape($video['title']); ?>"/>
                            </a>
                        <?php } ?>
                        <div class="caption">
                            <h4 itemprop="name" class="p-name">
                                <a itemprop="url" title="<?php echo $this->escape($video['title']); ?>"
                                   href="<?php echo $this->escape($video['videoUrl']); ?>">
                                    <?php echo $this->escape($video['title']); ?>
                                </a>
                            </h4>
                        </div>
                    </div>
                </div>
            <?php } ?>
        <?php } elseif ($block['list-type'] == 'vertical') { ?>
            <?php foreach ($block['resources'] as $video) { ?>
                <div class="col-sm-12 col-md-12 videoBox h-review" itemscope itemtype="http://schema.org/VideoObject">
                    <meta itemprop="thumbnail" content="<?php echo $this->escape($video['largeUrl']); ?>" />
                    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $video['time_publish'])); ?>" />
                    <meta itemprop="contentUrl" content="<?php echo $this->escape($video['videoFileUrl']); ?>" />
                    <div class="thumbnail">
                        <?php if ($video['image']) { ?>
                            <a itemprop="url" class="u-photo" title="<?php echo $this->escape($video['title']); ?>"
                               href="<?php echo $this->escape($video['videoUrl']); ?>">
                                <img itemprop="image" src="<?php echo $video['thumbUrl']; ?>"
                                     alt="<?php echo $this->escape($video['title']); ?>"/>
                            </a>
                        <?php } ?>
                        <div class="caption">
                            <h4 itemprop="name" class="p-name">
                                <a itemprop="url" title="<?php echo $this->escape($video['title']); ?>"
                                   href="<?php echo $this->escape($video['videoUrl']); ?>">
                                    <?php echo $this->escape($video['title']); ?>
                                </a>
                            </h4>
                        </div>
                    </div>
                </div>
            <?php } ?>
        <?php } elseif ($block['list-type'] == 'box') { ?>
            <?php $i = 1;?>
            <?php foreach($block['resources'] as $video) { ?>
                <?php if (in_array($i, array(1,11,21,31,41,51,61))) {
                    $class = 'col-md-6 col-sm-12 col-xs-12 videoBoxBig pull-left';
                    $img = $video['largeUrl'];
                } elseif (in_array($i, array(6,16,26,36,46,56,66))) {
                    $class = 'col-md-6 col-sm-12 col-xs-12 videoBoxBig pull-right';
                    $img = $video['largeUrl'];
                } else {
                    $class = 'col-md-3 col-sm-12 col-xs-12';
                    $img = $video['thumbUrl'];
                } ?>
                <div class="<?php echo $class;?> videoBox h-review" itemscope itemtype="http://schema.org/VideoObject">
                    <meta itemprop="thumbnail" content="<?php echo $this->escape($video['largeUrl']); ?>" />
                    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $video['time_publish'])); ?>" />
                    <meta itemprop="contentUrl" content="<?php echo $this->escape($video['videoFileUrl']); ?>" />
                    <div class="thumbnail">
                        <?php if($video['image']) { ?>
                            <a itemprop="url" class="u-photo" title="<?php echo $this->escape($video['title']); ?>" href="<?php echo $this->escape($video['videoUrl']); ?>">
                                <img itemprop="image" src="<?php echo $img; ?>" alt="<?php echo $this->escape($video['title']); ?>" />
                            </a>
                        <?php } ?>
                        <div class="caption">
                            <h4 itemprop="name" class="p-name">
                                <a itemprop="url" title="<?php echo $this->escape($video['title']); ?>" href="<?php echo $this->escape($video['videoUrl']); ?>"><?php echo $this->escape($video['title']); ?></a>
                            </h4>
                        </div>
                    </div>
                </div>
                <?php if (in_array($i, array(5,10,15,20,25,30,35,40,45,50,55,60,65,70))) { ?>
                    <div class="clearfix visible-xs-block"></div>
                <?php } ?>
                <?php $i++;?>
            <?php } ?>
        <?php } elseif ($block['list-type'] == 'list') { ?>
            <ul class="list-unstyled list-group">
                <?php foreach ($block['resources'] as $video) { ?>
                    <li class="p-name list-group-item" itemscope itemtype="http://schema.org/VideoObject">
                        <meta itemprop="thumbnail" content="<?php echo $this->escape($video['largeUrl']); ?>" />
                        <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $video['time_publish'])); ?>" />
                        <meta itemprop="contentUrl" content="<?php echo $this->escape($video['videoFileUrl']); ?>" />
                        <a itemprop="name" title="<?php echo $this->escape($video['title']); ?>"
                           href="<?php echo $this->escape($video['videoUrl']); ?>">
                            <?php echo $this->escape($video['title']); ?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        <?php } elseif ($block['list-type'] == 'slide') { ?>
            <?php if ($block['blockEffect']) {
                $this->jQuery(array(
                    'extension/owl.carousel.min.js',
                    'extension/owl.carousel.css',
                ));
                $this->js($this->assetModule('js/owl.carousel.config.js', 'video'));
                $this->css($this->assetModule('css/block.css', 'video'));
            } ?>
            <div class="owl-carousel itemImageAttach text-center clearfix hover-captions-container">
                <?php foreach ($block['resources'] as $video) { ?>
                    <div class="item h-review" itemscope itemtype="http://schema.org/VideoObject">
                        <meta itemprop="thumbnail" content="<?php echo $this->escape($video['largeUrl']); ?>" />
                        <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $video['time_publish'])); ?>" />
                        <meta itemprop="contentUrl" content="<?php echo $this->escape($video['videoFileUrl']); ?>" />
                        <div class="thumbnail p-item h-card">
                            <?php if ($video['image']) { ?>
                                <a itemprop="url" class="u-url" title="<?php echo $this->escape($video['title']); ?>"
                                   href="<?php echo $this->escape($video['videoUrl']); ?>">
                                    <img itemprop="image" class="img-responsive u-photo"
                                         src="<?php echo $this->escape($video['mediumUrl']); ?>"
                                         alt="<?php echo $this->escape($video['title']); ?>"/>
                                </a>
                            <?php } ?>
                            <h3 itemprop="name" class="p-name">
                                <a itemprop="url" class="u-url" title="<?php echo $this->escape($video['title']); ?>"
                                   href="<?php echo $this->escape($video['videoUrl']); ?>">
                                    <?php echo $this->escape($video['title']); ?>
                                </a>
                            </h3>
                        </div>
                    </div>
                <?php } ?>
            </div>
        <?php } elseif ($block['list-type'] == 'slidehover') { ?>
            <?php if ($block['blockEffect']) {
                $this->jQuery(array(
                    'extension/owl.carousel.min.js',
                    'extension/owl.carousel.css',
                ));
                $this->js($this->assetModule('js/owl.carousel.config.js', 'video'));
                $this->js($this->assetModule('js/caption.hover.js', 'video'));
            } ?>
            <div class="owl-carousel itemImageAttach text-center clearfix hover-captions-container">
                <?php foreach ($block['resources'] as $video) { ?>
                    <div class="item hover-captions hover-captions-slide" itemscope itemtype="http://schema.org/VideoObject">
                        <meta itemprop="thumbnail" content="<?php echo $this->escape($video['largeUrl']); ?>" />
                        <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $video['time_publish'])); ?>" />
                        <meta itemprop="contentUrl" content="<?php echo $this->escape($video['videoFileUrl']); ?>" />
                        <div class="hover-caption">
                            <h3 itemprop="name"><?php echo $this->escape($video['title']); ?></h3>
                            <p>
                                <a itemprop="url" class="u-url hover-caption-more"
                                   title="<?php echo $this->escape($video['title']); ?>"
                                   href="<?php echo $this->escape($video['videoUrl']); ?>">
                                    <?php echo _b('View'); ?>
                                </a>
                            </p>
                        </div>
                        <img itemprop="image" class="media-object img-responsive u-photo" src="<?php echo $video['mediumUrl']; ?>"
                             alt="<?php echo $this->escape($video['title']); ?>">
                    </div>
                <?php } ?>
            </div>
        <?php } elseif ($block['list-type'] == 'spotlight') { ?>
            <div class="video-spotlight">
                <?php $spotlight  = array_shift($block['resources']); ?>
                <?php $this->headScript()->appendFile($spotlight['qmeryScript']); ?>
                <div class="col-sm-12 col-md-12 h-review clearfix" itemscope itemtype="http://schema.org/VideoObject">
                    <meta itemprop="thumbnail" content="<?php echo $this->escape($spotlight['largeUrl']); ?>" />
                    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $spotlight['time_publish'])); ?>" />
                    <meta itemprop="contentUrl" content="<?php echo $this->escape($spotlight['videoFileUrl']); ?>" />
                    <div class="qmery-player">
                        <div class="qmery-player">
                            <div id="embed_qmery_player_<?php echo $this->escape($spotlight['video_qmery_id']); ?>"></div>
                            <div id="embed_qmery_player_icons<?php echo $this->escape($spotlight['video_qmery_id']); ?>"></div>
                        </div>
                    </div>
                </div>
                <?php if (!empty($block['resources'])) { ?>
                    <?php foreach ($block['resources'] as $video) { ?>
                        <div class="col-sm-6 col-md-4 videoBox h-review" itemscope itemtype="http://schema.org/VideoObject">
                            <meta itemprop="thumbnail" content="<?php echo $this->escape($video['largeUrl']); ?>" />
                            <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $video['time_publish'])); ?>" />
                            <meta itemprop="contentUrl" content="<?php echo $this->escape($video['videoFileUrl']); ?>" />
                            <div class="thumbnail">
                                <?php if ($video['image']) { ?>
                                    <a itemprop="url" class="u-photo" title="<?php echo $this->escape($video['title']); ?>"
                                       href="<?php echo $this->escape($video['videoUrl']); ?>">
                                        <img itemprop="image" src="<?php echo $video['thumbUrl']; ?>"
                                             alt="<?php echo $this->escape($video['title']); ?>"/>
                                    </a>
                                <?php } ?>
                                <div class="caption">
                                    <h4 itemprop="name" class="p-name">
                                        <a itemprop="url" title="<?php echo $this->escape($video['title']); ?>"
                                           href="<?php echo $this->escape($video['videoUrl']); ?>">
                                            <?php echo $this->escape($video['title']); ?>
                                        </a>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
    <?php if ($block['more-show'] && !empty($block['more-link'])) { ?>
        <div class="video-block-more clearfix">
            <a title="<?php echo _b('More videos'); ?>"
               href="<?php echo $block['more-link']; ?>"><?php echo _b('More videos'); ?></a>
        </div>
    <?php } ?>
</div>