<?php if ($block['resources']['server']['type'] == 'qmery') {
    $this->jQuery();
    $this->headScript()->appendFile($block['resources']);
} ?>
<div class="video-block video-block-select">
    <div class="clearfix">
        <meta itemprop="name" content="<?php echo $this->escape($block['resources']['largeUrl']); ?>" />
        <meta itemprop="thumbnail" content="<?php echo $this->escape($block['resources']['largeUrl']); ?>" />
        <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $block['resources']['time_publish'])); ?>" />
        <meta itemprop="contentUrl" content="<?php echo $this->escape($block['resources']['videoFileUrl']); ?>" />
        <?php if ($block['resources']['server']['type'] == 'qmery') { ?>
        <div class="qmery-player">
            <div id="embed_qmery_player_<?php echo $this->escape($block['resources']['video_qmery_id']); ?>"></div>
            <div id="embed_qmery_player_icons<?php echo $this->escape($block['resources']['video_qmery_id']); ?>"></div>
        </div>
        <?php } ?>
    </div>
</div>