<?php if (isset($attribute['all']) && !empty($attribute['all'])) { ?>
    <div class="clearfix">
        <div class="product-attribute">
            <?php foreach ($attribute['all'] as $attributeSingle) { ?>
                <div class="product-attribute-head">
                    <h2><i class="far fa-caret-square-left"></i> <?php echo $attributeSingle['title']; ?></h2>
                </div>
                <table class="table table-striped table-bordered table-hover table-sm">
                    <?php foreach ($attributeSingle['info'] as $field) { ?>
                        <?php if (!empty($field['data'])) { ?>
                            <tr>
                                <?php if ($field['type'] == 'text' || $field['type'] == 'select') { ?>
                                    <td class="col-4 attribute-title">
                                        <?php if ($field['icon']) { ?>
                                            <i class="fas<?php echo $field['icon']; ?>"></i>
                                        <?php } elseif ($field['image']) { ?>
                                            <img src="<?php echo $field['image']; ?>"
                                                 alt="<?php echo $field['title']; ?>">
                                        <?php } ?>
                                        <?php echo $field['title']; ?>
                                    </td>
                                    <td class="col-8 attribute-body"><?php echo $field['data']; ?></td>
                                <?php } elseif ($field['type'] == 'link') { ?>
                                    <td class="col-12 attribute-body" colspan="2">
                                        <?php if ($field['icon']) { ?>
                                            <i class="fas<?php echo $field['icon']; ?>"></i>
                                        <?php } elseif ($field['image']) { ?>
                                            <img src="<?php echo $field['image']; ?>"
                                                 alt="<?php echo $field['title']; ?>">
                                        <?php } ?>
                                        <a
                                                title="<?php echo $field['title']; ?>"
                                                href="<?php echo $field['data']; ?>"
                                                target="_blank"><?php echo $field['title']; ?></a></td>
                                <?php } elseif ($field['type'] == 'file') { ?>
                                    <td class="col-12 attribute-body" colspan="2">
                                        <?php if ($field['icon']) { ?>
                                            <i class="fas<?php echo $field['icon']; ?>"></i>
                                        <?php } elseif ($field['image']) { ?>
                                            <img src="<?php echo $field['image']; ?>"
                                                 alt="<?php echo $field['title']; ?>">
                                        <?php } ?>
                                        <a
                                                title="<?php echo $field['title']; ?>"
                                                href="<?php echo $field['data']; ?>"><?php echo $field['title']; ?></a>
                                    </td>
                                <?php } elseif ($field['type'] == 'currency') { ?>
                                    <td class="col-4 attribute-title">
                                        <?php if ($field['icon']) { ?>
                                            <i class="fas<?php echo $field['icon']; ?>"></i>
                                        <?php } elseif ($field['image']) { ?>
                                            <img src="<?php echo $field['image']; ?>"
                                                 alt="<?php echo $field['title']; ?>">
                                        <?php } ?>
                                        <?php echo $field['title']; ?>
                                    </td>
                                    <td class="col-8 attribute-body"><?php echo $this->currencyFormat($field['data'], "USD", "en_US"); ?></td>
                                <?php } elseif ($field['type'] == 'date') { ?>
                                    <td class="col-4 attribute-title">
                                        <?php echo $field['title']; ?>
                                        <?php if ($field['icon']) { ?>
                                            <i class="fas<?php echo $field['icon']; ?>"></i>
                                        <?php } elseif ($field['image']) { ?>
                                            <img src="<?php echo $field['image']; ?>"
                                                 alt="<?php echo $field['title']; ?>">
                                        <?php } ?>
                                    </td>
                                    <td class="col-8 attribute-body"><?php echo $this->dateFormat(
                                            $field['data'], IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, "en_US"
                                        ); ?></td>
                                <?php } elseif ($field['type'] == 'number') { ?>
                                    <td class="col-4 attribute-title">
                                        <?php echo $field['title']; ?>
                                        <?php if ($field['icon']) { ?>
                                            <i class="fas<?php echo $field['icon']; ?>"></i>
                                        <?php } elseif ($field['image']) { ?>
                                            <img src="<?php echo $field['image']; ?>"
                                                 alt="<?php echo $field['title']; ?>">
                                        <?php } ?>
                                    </td>
                                    <td class="col-8 attribute-body"><?php echo $this->numberFormat(
                                            $field['data'], NumberFormatter::PATTERN_DECIMAL, NumberFormatter::TYPE_DEFAULT, "en_US"
                                        ); ?></td>
                                <?php } elseif ($field['type'] == 'checkbox') { ?>
                                    <?php if ($field['data']) { ?>
                                        <td class="col-12 attribute-body"
                                            colspan="2">
                                            <?php echo $field['title']; ?>
                                            <?php if ($field['icon']) { ?>
                                                <i class="fas<?php echo $field['icon']; ?>"></i>
                                            <?php } elseif ($field['image']) { ?>
                                                <img src="<?php echo $field['image']; ?>"
                                                     alt="<?php echo $field['title']; ?>">
                                            <?php } ?>
                                        </td>
                                    <?php } ?>
                                <?php } ?>
                            </tr>
                        <?php } ?>
                    <?php } ?>
                </table>
            <?php } ?>
        </div>
    </div>
<?php } ?>