<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="col-3">
        <?php $sideActive = 'video'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-9">
        <div class="card card-body bg-light mb-3">
            <ul class="nav nav-pills bg-light mb-3 p-3">
                <li class="nav-item">
                    <a class="nav-link <?php if ($nav['page'] == 'update') {
                        echo 'active';
                    } ?>" href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><?php _e('Edit basic information'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?php if ($nav['page'] == 'additional') {
                        echo 'active';
                    } ?>" href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><?php _e('Edit additional information'); ?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?php if ($nav['page'] == 'finish') {
                        echo 'active';
                    } ?>" href="<?php echo $this->url('', ['action' => 'finish', 'id' => $video['id']]); ?>"><?php _e('Watch submitted video'); ?></a>
                </li>
            </ul>
        </div>
        <?php echo $this->form($form); ?>
    </div>
</div>