<?php
$this->jquery();
$this->css($this->assetModule('css/front.css'));
$this->js(
    [
        $this->assetModule('js/jquery.form.js'),
        $this->assetModule('js/progress-bar.js'),
    ]
);
$script
                    = <<<'EOT'
    $('#videoFile').on('change', function (e) {
        var file = this.files[0];
        var fileSize = (file.size / 1000000).toFixed(2);
        var fileExtension = file.name.split('.').pop().toLowerCase();
        $('.fileInformation').removeClass('hidden');
        $('.fileInformationSize').text("%s " + fileSize + " MB " + " %s " + fileExtension);
        if (file.size > %s) {
            $('.fileInformationSizeError').removeClass('hidden');
            $('.fileInformationSizeError').text("%s");
            var fileSizeOk = 0;
            e.preventDefault();
        } else {
            $('.fileInformationSizeError').addClass('hidden');
            $('.fileInformationSizeError').text(' ');
            var fileSizeOk = 1;
            e.preventDefault();
        }
        if($.inArray(fileExtension, ['mp3','mp4']) == -1) {
            $('.fileInformationExtensionError').removeClass('hidden');
            $('.fileInformationExtensionError').text("%s");
            var fileExtensionOk = 0;
            e.preventDefault();
        } else {
            $('.fileInformationExtensionError').addClass('hidden');
            $('.fileInformationExtensionError').text(' ');
            var fileExtensionOk = 1;
            e.preventDefault();
        }
        if (fileSizeOk  == 1 && fileExtensionOk == 1) {
            $('.videoUpload').removeAttr("disabled");
        } else {
           $('.videoUpload').attr('disabled', true);
        }
    });
EOT;
$fileSize           = __('Your selected file size is');
$fileExtension      = __('And file extension is');
$fileSizeError      = sprintf(__('You attach to large file, allowed upload size is %s'), number_format($config['media_size'] / 1000000, 2) . ' MB');
$fileExtensionError = sprintf(__('You attach wrong file, allowed extensions is %s'), $config['media_extension']);
$script             = sprintf($script, $fileSize, $fileExtension, $config['media_size'], $fileSizeError, $fileExtensionError);
$this->footScript()->appendScript($script);
?>
<div class="clearfix">
    <div class="col-3">
        <?php $sideActive = 'video'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-9">
        <div class="card card-body bg-light mb-3">
            <ul class="nav nav-pills bg-light mb-3 p-3">
                <li class="nav-item"><a class="nav-link active" href="<?php echo $this->url('', ['action' => 'upload']); ?>"><?php _e('Upload video'); ?></a>
                </li>
                <li class="nav-item"><a class="nav-link" href="#"><?php _e('Add basic information'); ?></a></li>
                <li class="nav-item"><a class="nav-link" href="#"><?php _e('Add additional information'); ?></a></li>
                <li class="nav-item"><a class="nav-link" href="#"><?php _e('Watch submitted video'); ?></a></li>
            </ul>
        </div>
        <div class="page-header mb-3">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
        <div class="alert alert-info">
            <?php echo sprintf(
                __('You just allow upload media with <strong>%s</strong> extensions, maximum upload size is <strong>%s</strong>'), $config['media_extension'],
                number_format($config['media_size'] / 1000000, 2) . ' MB'
            ) ?>
        </div>
        <div class="card card-body bg-light mb-3">
            <div class="fileInformation hidden">
                <div class="fileInformationSize text-success"></div>
                <div class="fileInformationSizeError text-danger hidden"></div>
                <div class="fileInformationExtensionError text-danger hidden"></div>
            </div>
            <?php echo $this->form($form, 'inline'); ?>
        </div>
        <div id="progress-bar" class="progress">
            <div id="bar" class="progress-bar bg-success bg-striped active" role="progressbar"
                 aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                <div id="percent">0%</div>
            </div>
        </div>
    </div>
</div>