<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="col-xs-3">
        <?php $sideActive = 'video'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-xs-9">
        <div class="well well-sm">
            <ul class="nav nav-pills">
                <li<?php if ($nav['page'] == 'update') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['action' => 'update', 'id' => $video['id']]); ?>"><?php _e('Edit basic information'); ?></a>
                </li>
                <li<?php if ($nav['page'] == 'additional') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['action' => 'additional', 'id' => $video['id']]); ?>"><?php _e('Edit additional information'); ?></a>
                </li>
                <li<?php if ($nav['page'] == 'finish') {
                    echo ' class="active"';
                } ?>>
                    <a href="<?php echo $this->url('', ['action' => 'finish', 'id' => $video['id']]); ?>"><?php _e('Watch submitted video'); ?></a>
                </li>
            </ul>
        </div>
        <div class="page-header">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
        <div class="video-submit-form alert alert-warning">
            <h4><?php _e('Congratulations'); ?></h4>
            <p><?php _e('Your submit video save on our system successfully. this video not published on website yet and will publish after admin review. please wait to website admin and do not submit this file again'); ?></p>
        </div>
        <div class="text-center video-player-box clearfix">
            <div class="col-xs-10 col-xs-offset-1">
                <?php echo $this->videojs($video['videoFileUrl'], $video['largeUrl']); ?>
            </div>
        </div>
        <div class="text-center">
            <br/>
            <a class="btn btn-success btn-lg"
               href="<?php echo $this->url('', ['controller' => 'index']); ?>"><?php _e('Finish'); ?></a>
        </div>
    </div>
</div>