<?php
$this->css($this->assetModule('css/front.css'));
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($this->escape($videoSingle['title']), 'og:title', 'property');
$this->headMeta($this->escape($videoSingle['videoUrl']), 'og:url', 'property');
$this->headMeta('video', 'og:type', 'property');
$this->headMeta($this->escape($videoSingle['video_url']), 'og:video:url', 'property');
$this->headMeta($this->escape($videoSingle['video_url']), 'og:video:secure_url', 'property');
$this->headMeta('video/mp4', 'og:video:type', 'property');

if (isset($videoSingle['video_duration']) && !empty($videoSingle['video_duration'])) {
    //$this->headMeta(_strip($videoSingle['video_duration']), 'video:duration', 'property');
}
if (isset($videoSingle['largeUrl']) && !empty($videoSingle['largeUrl'])) {
    $this->headMeta($this->escape($videoSingle['largeUrl']), 'og:image', 'property');
}
if (isset($videoSingle['largeUrl']) && !empty($videoSingle['largeUrl'])) {
    $this->headMeta($this->escape($videoSingle['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta('player', 'twitter:card');
$this->headMeta($this->escape($videoSingle['title']), 'twitter:title');
if (isset($videoSingle['text_summary']) && !empty($videoSingle['text_summary'])) {
    $this->headMeta(_strip($videoSingle['text_summary']), 'twitter:description');
}
if (isset($videoSingle['largeUrl']) && !empty($videoSingle['largeUrl'])) {
    $this->headMeta($this->escape($videoSingle['largeUrl']), 'twitter:image');
}
$this->headMeta($this->escape($videoSingle['videoUrl']), 'twitter:player');

// Load player
echo $this->video($videoSingle['player']);