<?php
$this->css($this->assetModule('css/front.css'));
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($this->escape($videoItem['title']), 'og:title', 'property');
$this->headMeta($this->escape($videoItem['videoUrl']), 'og:url', 'property');
$this->headMeta('video', 'og:type', 'property');
$this->headMeta($this->escape($videoItem['videoFileUrl']), 'og:video:url', 'property');
$this->headMeta($this->escape($videoItem['videoFileUrl']), 'og:video:secure_url', 'property');

if ($videoItem['video_type'] == 'video') {
    $this->headMeta('video/mp4', 'og:video:type', 'property');
} elseif ($videoItem['video_type'] == 'audio') {
    $this->headMeta('audio/mp3', 'og:video:type', 'property');
}
if (isset($videoItem['video_duration']) && !empty($videoItem['video_duration'])) {
    //$this->headMeta(_strip($videoItem['video_duration']), 'video:duration', 'property');
}
if (isset($videoItem['largeUrl']) && !empty($videoItem['largeUrl'])) {
    $this->headMeta($this->escape($videoItem['largeUrl']), 'og:image', 'property');
}
if (isset($videoItem['largeUrl']) && !empty($videoItem['largeUrl'])) {
    $this->headMeta($this->escape($videoItem['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta('player', 'twitter:card');
$this->headMeta($this->escape($videoItem['title']), 'twitter:title');
if (isset($videoItem['text_summary']) && !empty($videoItem['text_summary'])) {
    $this->headMeta(_strip($videoItem['text_summary']), 'twitter:description');
}
if (isset($videoItem['largeUrl']) && !empty($videoItem['largeUrl'])) {
    $this->headMeta($this->escape($videoItem['largeUrl']), 'twitter:image');
}
$this->headMeta($this->escape($videoItem['videoUrl']), 'twitter:player');

if ($videoItem['server']['type'] == 'qmery') {
    $this->jQuery();
    $this->headScript()->appendFile($videoItem['qmeryScript']);
}
?>
<div class="text-center video-player">
    <?php if ($videoItem['server']['type'] == 'file') { ?>
        <?php echo $this->videojs($videoItem['videoFileUrl'], $videoItem['largeUrl']); ?>
    <?php } elseif ($videoItem['server']['type'] == 'qmery') { ?>
        <?php if (isset($videoItem['server']['qmery_player_type']) && $videoItem['server']['qmery_player_type'] == 'iframe') { ?>
            <div class="clearfix">
                <iframe src="<?php echo $this->escape($videoItem['qmeryDirect']); ?>" allowtransparency="true" scrolling="no" name="qmery_embed_video" allowfullscreen="" mozallowfullscreen="" webkitallowfullscreen="" oallowfullscreen="" msallowfullscreen="" frameborder="0" height="100%" width="100%"></iframe>
            </div>
        <?php } else { ?>
            <div class="qmery-player-min-height">
                <div class="qmery-player-full-height">
                    <div class="qmery-player">
                        <div id="embed_qmery_player_<?php echo $this->escape($videoItem['video_qmery_id']); ?>"></div>
                        <div id="embed_qmery_player_icons<?php echo $this->escape($videoItem['video_qmery_id']); ?>"></div>
                    </div>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
</div>