<?php
$this->css($this->assetModule('css/front.css'));
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($this->escape($videoSingle['title']), 'og:title', 'property');
$this->headMeta($this->escape($videoSingle['videoUrl']), 'og:url', 'property');
$this->headMeta('video', 'og:type', 'property');
$this->headMeta($this->escape($videoSingle['video_url']), 'og:video:url', 'property');
$this->headMeta($this->escape($videoSingle['video_url']), 'og:video:secure_url', 'property');
$this->headMeta('video/mp4', 'og:video:type', 'property');

if (isset($videoSingle['video_duration']) && !empty($videoSingle['video_duration'])) {
    //$this->headMeta(_strip($videoSingle['video_duration']), 'video:duration', 'property');
}
if (isset($videoSingle['largeUrl']) && !empty($videoSingle['largeUrl'])) {
    $this->headMeta($this->escape($videoSingle['largeUrl']), 'og:image', 'property');
}
if (isset($videoSingle['largeUrl']) && !empty($videoSingle['largeUrl'])) {
    $this->headMeta($this->escape($videoSingle['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta('player', 'twitter:card');
$this->headMeta($this->escape($videoSingle['title']), 'twitter:title');
if (isset($videoSingle['text_summary']) && !empty($videoSingle['text_summary'])) {
    $this->headMeta(_strip($videoSingle['text_summary']), 'twitter:description');
}
if (isset($videoSingle['largeUrl']) && !empty($videoSingle['largeUrl'])) {
    $this->headMeta($this->escape($videoSingle['largeUrl']), 'twitter:image');
}
$this->headMeta($this->escape($videoSingle['videoUrl']), 'twitter:player');
?>
<div class="clearfix video-page" itemscope itemtype="https://schema.org/VideoObject">
    <div class="page-header mb-3">
        <h1 itemprop="name"><?php echo $this->escape($videoSingle['title']); ?></h1>
    </div>
    <meta itemprop="thumbnail" content="<?php echo $this->escape($videoSingle['largeUrl']); ?>"/>
    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $videoSingle['time_create'])); ?>"/>
    <meta itemprop="contentUrl" content="<?php echo $this->escape($videoSingle['video_url']); ?>"/>
    <div class="row clearfix">
        <div class="col-lg-8 col-md-8 col-12">
            <div class="clearfix video-information">
                <ul class="text-muted list-inline small">
                    <li class="list-inline-item"><i class="fas fa-calendar"></i> <?php echo $this->escape($videoSingle['time_update_view']); ?></li>
                    <li class="list-inline-item"><i class="fas fa-eye"></i> <?php echo _number($this->escape($videoSingle['hits'])); ?></li>
                    <li class="list-inline-item"><i class="far fa-clock"></i> <?php echo $this->escape($videoSingle['video_duration_view']); ?>
                    </li>
                    <li class="list-inline-item"><i class="fas fa-folder"></i></li>
                    <?php foreach ($videoSingle['categories'] as $videoCategory) { ?>
                        <li class="p-category list-inline-item" itemprop="about">
                            <a title="<?php echo $this->escape($videoCategory['title']); ?>"
                               href="<?php echo $this->escape($videoCategory['url']); ?>">
                                <?php echo $this->escape($videoCategory['title']); ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <?php if ($access) { ?>
                <div class="text-center video-player">
                    <div class="clearfix">
                        <?php echo $this->video($videoSingle['player']); ?>
                    </div>
                </div>
            <?php } else { ?>
                <div class="clearfix">
                    <div class="mb-3 text-center">
                        <img class="img-fluid" src="<?php echo $this->escape($videoSingle['largeUrl']); ?>" alt="<?php echo $this->escape($videoSingle['title']); ?>">
                    </div>
                    <div class="card text-center bg-light mb-3">
                        <div class="card-body">
                            <h5 class="card-title">
                                <?php _e('Fee'); ?> : <?php echo $this->escape($videoSingle['sale_price_view']); ?>
                            </h5>
                            <p class="card-text">
                                <?php _e('This is paid video and you dont have access to watch it, use buy button to paid and watch this video'); ?>
                            </p>
                            <a href="<?php echo $this->escape($videoSingle['payUrl']); ?>" class="btn btn-primary">
                                <?php _e('Pay and watch video'); ?>
                            </a>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="clearfix video-info-list">
                <ul class="list-inline">
                    <?php if (!empty($vote)) { ?>
                        <li class="col-lg-3 col-md-3 col-6 list-inline-item">
                            <?php include $this->template('votebar.phtml', 'front', 'vote'); ?>
                        </li>
                    <?php } ?>
                    <?php if (!empty($favourite)) { ?>
                        <li class="col-lg-3 col-md-3 col-6 list-inline-item">
                            <?php include $this->template('favouritebar.phtml', 'front', 'favourite'); ?>
                        </li>
                    <?php } ?>
                    <?php if ($config['social_sharing']) { ?>
                        <li class="col-lg-6 col-md-6 col-12 list-inline-item">
                            <div class="socialSharing">
                                <?php echo $this->socialSharing(
                                    $config['social_sharing'],
                                    $this->escape($videoSingle['title']),
                                    $this->escape($videoSingle['videoUrl']),
                                    $this->escape($videoSingle['largeUrl'])
                                ); ?>
                            </div>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <?php if (!empty($videoSingle['text_summary']) || !empty($videoSingle['text_description']) || !empty($categorySingle['text_description'])) { ?>
                <div class="card card-body bg-light mb-3 clearfix">
                    <h2><?php _e('Description'); ?></h2>
                    <div class="clearfix video-info-box" itemprop="description">
                        <?php echo $videoSingle['text_summary']; ?>
                    </div>
                    <div class="clearfix video-info-box" itemprop="description">
                        <?php echo $videoSingle['text_description']; ?>
                    </div>
                    <?php if ($config['view_description_video'] && !empty($categorySingle['text_description'])) { ?>
                        <div class="video-info-box p-review clearfix" itemprop="description">
                            <?php echo $categorySingle['text_description']; ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
            <?php include $this->template('front/tag'); ?>
        </div>
        <div class="col-lg-4 col-md-4 col-12 mb-5">
            <?php include $this->template('front/playlist'); ?>
            <?php /* <div class="video-channel" itemprop="author" itemscope itemtype="https://schema.org/Person">
                <a title="<?php _e('User channel'); ?>" href="<?php echo $this->escape($videoSingle['channelUrl']); ?>">
                    <?php echo $submitter['avatar']; ?>
                    <?php echo sprintf(__('%s channel'), $this->escape($submitter['name'])); ?>
                </a>
                <meta itemprop="name" content="<?php echo $this->escape($submitter['name']); ?>" />
            </div> */ ?>
            <?php include $this->template('front/attribute'); ?>
            <?php include $this->template('front/video-related'); ?>
        </div>
    </div>
</div>
