<?php
// Load header files
$this->jQuery();
$this->css($this->assetModule('css/front.css'));
?>
<div class="clearfix row">
    <div class="clearfix">
        <div class="video-list clearfix">
            <?php if (isset($videoTitleH1) && !empty($videoTitleH1)) { ?>
                <div class="page-header mb-3 mb-3">
                    <h1><?php echo $videoTitleH1; ?></h1>
                </div>
            <?php } elseif (isset($videoTitleH2) && !empty($videoTitleH2)) { ?>
                <div class="page-header mb-3 mb-3">
                    <h2><?php echo $videoTitleH2; ?></h2>
                </div>
            <?php } ?>
            <?php if (!empty($config['text_description_index']) && isset($showIndexDesc) && $showIndexDesc == 1 && isset($page) && $page == 1) { ?>
                <div class="card card-body bg-light mb-3 videoIndexDescription">
                    <?php echo $config['text_description_index']; ?>
                </div>
            <?php } ?>
            <?php if (isset($categories) && !empty($categories) && isset($categoryTree) && !empty($categoryTree)) { ?>
                <div class="clearfix row">
                    <?php foreach ($categoryTree as $category) { ?>
                        <div class="col-12 col-md-4" itemscope itemtype="https://schema.org/Brand">
                            <div class="card bg-light mb-3">
                                <?php if (isset($category['image']) && !empty($category['image'])) { ?>
                                    <a itemprop="url" href="<?php echo $this->escape($category['categoryUrl']); ?>" title="<?php echo $this->escape($category['title']); ?>">
                                        <img itemprop="image" src="<?php echo $this->escape($category['mediumUrl']); ?>" alt="<?php echo $this->escape($category['title']); ?>" class="card-img-top">
                                    </a>
                                <?php } ?>
                                <div class="card-body text-justify">
                                    <h3 class="p-name card-title mb-3" itemprop="name">
                                        <a href="<?php echo $this->escape($category['categoryUrl']); ?>" title="<?php echo $this->escape($category['title']); ?>">
                                            <?php echo $this->escape($category['title']); ?>
                                        </a>
                                    </h3>
                                    <div class="card-text mb-3">
                                        <?php $summery = $this->escape($category['text_summary']);
                                        if (empty($summery)) {
                                            $summery = $category['text_description'];
                                        } ?>
                                        <?php if (!empty($summery)) { ?>
                                            <?php echo $summery; ?>
                                        <?php } ?>
                                    </div>
                                    <div class="card-text text-center">
                                        <a class="btn btn-primary btn-sm" href="<?php echo $this->escape($category['categoryUrl']); ?>" title="<?php echo $this->escape($category['title']); ?>">
                                            <?php echo $this->escape($category['title']); ?>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <div class="alert alert-warning" role="alert">
                    <?php _e('No category has been made on this part yet. please check this page later'); ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>