<?php
// Load angular custom js
$script
        = <<<'EOT'
var app = angular.module('video', ['angularUtils.directives.dirPagination']);
app.controller('listdata',function($scope, $http){
    $scope.videos = [];
    $('.ajax-spinner').show();
    $http.get("%s").success(function(response){
        $scope.videos = response;
        $('.ajax-spinner').hide();
    });
    $scope.sortKey = "%s";
    $scope.reverse = true;
    $scope.sort = function(keyname){
        $scope.sortKey = keyname;
        $scope.reverse = !$scope.reverse;
    }
});
EOT;
$script = sprintf(
    $script,
    $filterUrl,
    'time_create'
);

$scriptMenu
            = <<<'EOT'
$(function() {
    var json = '%s';
    $('#category-tree-view').treeview({
        levels: 1,
        data: json,
        enableLinks: true,
        expandIcon: 'fas fa-plus',
		collapseIcon: 'fas fa-minus',
		emptyIcon: 'fa',
		checkedIcon: 'far fa-check-square',
		uncheckedIcon: 'far fa-square',
    });
});
EOT;
$scriptMenu = sprintf(
    $scriptMenu,
    $categoriesJson
);

// Load header files
$this->jQuery();
$this->angular();
$this->js(
    [
        $this->assetModule('js/dirPagination.js'),
        $this->assetModule('js/bootstrap-treeview.min.js'),
    ]
);
$this->css($this->assetModule('css/front.css'));
$this->footScript()->appendScript($script);
$this->footScript()->appendScript($scriptMenu);
// Set box site
switch ($config['view_column']) {
    case 1:
        $videoBoxSize = 'col-12';
        break;

    case 2:
        $videoBoxSize = 'col-6';
        break;

    case 3:
        $videoBoxSize = 'col-4';
        break;

    case 4:
        $videoBoxSize = 'col-3';
        break;

    case 5:
        $videoBoxSize = 'col-2';
        break;
}
?>
<div class="clearfix row">
    <div class="ajax-spinner">
        <img src="<?php echo $this->assetModule('image/spinner.gif'); ?>" class="ajax-spinner-loader"/>
    </div>
    <div class="col-12">
        <?php include $this->template('front/category'); ?>
        <?php include $this->template('front/user'); ?>
    </div>
    <div class="col-3">
        <div class="video-search-form card card-body bg-light mb-3 clearfix">
            <div class="page-header">
                <h4><?php _e('Search on this group'); ?></h4>
            </div>
            <form>
                <div class="form-group">
                    <label><i class="fas fa-search"></i> <?php _e('Title'); ?></label>
                    <input type="text" ng-model="filterTitle" class="form-control">
                </div>
                <?php $filterNameArray = []; ?>
                <?php foreach ($filterList as $singleFilter) { ?>
                    <?php if ($singleFilter['type'] == 'select') { ?>
                        <?php
                        $filterName        = 'filter' . $singleFilter['name'];
                        $filterNameArray[] = [
                            'fieldName'  => $singleFilter['name'],
                            'filterName' => $filterName,
                        ];
                        ?>
                        <div class="form-group">
                            <label>
                                <?php if ($singleFilter['icon']) { ?>
                                    <i class="fas<?php echo $singleFilter['icon']; ?>"></i>
                                <?php } elseif ($singleFilter['image']) { ?>
                                    <img src="<?php echo $singleFilter['image']; ?>"
                                         alt="<?php echo $singleFilter['title']; ?>">
                                <?php } ?>
                                <?php echo $singleFilter['title']; ?>
                            </label>
                            <select ng-model="<?php echo $filterName; ?>" class="form-control">
                                <option value=""><?php _e('All'); ?></option>
                                <?php foreach ($singleFilter['value']['data'] as $valueData) { ?>
                                    <?php if (!empty($valueData)) { ?>
                                        <option ng-click="sort('<?php echo $valueData; ?>')"><?php echo $valueData; ?></option>
                                    <?php } ?>
                                <?php } ?>
                            </select>
                        </div>
                    <?php } elseif ($singleFilter['type'] == 'text') { ?>
                        <div class="form-group">
                            <?php
                            $filterName        = 'filter' . $singleFilter['name'];
                            $filterNameArray[] = [
                                'fieldName'  => $singleFilter['name'],
                                'filterName' => $filterName,
                            ];
                            ?>
                            <label>
                                <?php if ($singleFilter['icon']) { ?>
                                    <i class="fas<?php echo $singleFilter['icon']; ?>"></i>
                                <?php } elseif ($singleFilter['image']) { ?>
                                    <img src="<?php echo $singleFilter['image']; ?>"
                                         alt="<?php echo $singleFilter['title']; ?>">
                                <?php } ?>
                                <?php echo $singleFilter['title']; ?>
                            </label>
                            <input type="text" ng-model="<?php echo $filterName; ?>" class="form-control">
                        </div>
                    <?php } ?>
                <?php } ?>
            </form>
        </div>
        <div class="clearfix category-list">
            <div class="page-header">
                <h4><?php _e('Category list'); ?></h4>
            </div>
            <div class="clearfix">
                <div id="category-tree-view"></div>
            </div>
        </div>
    </div>
    <div class="col-9" ng-controller="listdata">
        <div class="clearfix">
            <div class="video-list clearfix">
                <?php if (isset($videoTitleH1) && !empty($videoTitleH1)) { ?>
                    <div class="page-header">
                        <h1><?php echo $videoTitleH1; ?></h1>
                    </div>
                <?php } elseif (isset($videoTitleH2) && !empty($videoTitleH2)) { ?>
                    <div class="page-header">
                        <h2><?php echo $videoTitleH2; ?></h2>
                    </div>
                <?php } ?>
                <?php if (!empty($config['text_description_index']) && isset($showIndexDesc) && $showIndexDesc == 1 && isset($page) && $page == 1) { ?>
                    <div class="card card-body bg-light mb-3 videoIndexDescription">
                        <?php echo $config['text_description_index']; ?>
                    </div>
                <?php } ?>
                <div class="clearfix video-sort">
                    <ul class="list-inline">
                        <li class="list-inline-item"><?php _e('Sort by'); ?> :</li>
                        <li class="list-inline-item video-sort-type" ng-click="sort('time_create')"><?php _e('Time'); ?> <i
                                    class="fassort-icon" ng-show="sortKey=='time_create'"
                                    ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="list-inline-item video-sort-type" ng-click="sort('hits')"><?php _e('Hits'); ?> <i class="fassort-icon"
                                                                                                                     ng-show="sortKey=='hits'"
                                                                                                                     ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i>
                        </li>
                        <li class="list-inline-item video-sort-type" ng-click="sort('favourite')"><?php _e('Favourite'); ?> <i
                                    class="fassort-icon" ng-show="sortKey=='favourite'"
                                    ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="list-inline-item video-sort-type" ng-click="sort('title')"><?php _e('Title'); ?> <i
                                    class="fassort-icon" ng-show="sortKey=='title'"
                                    ng-class="{'fa-caret-up':reverse,'fa-caret-down':!reverse}"></i></li>
                        <li class="list-inline-item video-sort-type" ng-click="sortKey=''"><?php _e('Default'); ?></li>
                    </ul>
                </div>
                <div class="row">
                    <div dir-paginate="video in videos|orderBy:sortKey:reverse|filter: {<?php if (!empty($filterNameArray)) { ?><?php foreach (
                        $filterNameArray as $filterNameSingle
                    )
                    { ?><?php echo $filterNameSingle['fieldName'] ?> : <?php echo $filterNameSingle['filterName'] ?>,<?php } ?><?php } ?> title : filterTitle, marketable : filterMarketable } |itemsPerPage:<?php echo $config['view_perpage']; ?>"
                         class="<?php echo $videoBoxSize; ?> video-box h-video" itemscope
                         itemtype="https://schema.org/VideoObject">
                        <div class="thumbnail" ng-mouseover="hoverCompare = true" ng-mouseleave="hoverCompare = false">
                            <a itemprop="url" class="u-photo" title="{{video.title}}" href="{{video.videoUrl}}"
                               target="_blank">
                                <img itemprop="image thumbnail" src="{{video.thumbUrl}}" alt="{{video.title}}"/>
                            </a>
                            <div class="caption">
                                <h3 class="p-name" itemprop="name">
                                    <a title="{{video.title}}" href="{{video.videoUrl}}" target="_blank">
                                        {{video.title}}
                                    </a>
                                </h3>
                                <meta itemprop="duration" content="T1M33S"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="paginator">
                <dir-pagination-controls
                        max-size="<?php echo $config['view_perpage']; ?>"
                        direction-links="true"
                        boundary-links="true">
                </dir-pagination-controls>
            </div>
        </div>
    </div>
</div>