<?php
// Load header files
$this->jQuery();
$this->angular(array(
    'angular-route.js',
    'ui-bootstrap-custom-tpls-0.7.0.js',
    'pi.js',
    'i18n'
));
$this->js($this->assetModule('js/bootstrap-treeview.min.js'));
$this->css($this->assetModule('css/front.css'));
?>
<div ng-view></div>
<script>
    angular
        .module('video', ['ngRoute', 'ui.bootstrap', 'pi'])
        .constant('config', {
            pageType: '<?php echo $pageType; ?>',
            urlRoot: '<?php echo Pi::url($this->url('', array('controller' => 'json', 'action' => 'var'))); ?>'.replace(/var\/?$/, ''),
            urlCompare: '<?php echo Pi::url($this->url('', array('controller' => 'compare'))); ?>',
            assetRoot: '<?php echo $this->assetModule('ng-template/front/', '', false); ?>',
            categoryJson: '<?php echo $categoriesJson; ?>',
            categorySlug: '<?php echo isset($category) ? $category['slug'] : '' ?>',
            tagTerm: '<?php echo isset($tag) ? $tag : '' ?>',
            uid: '<?php echo isset($uid) ? $uid : Pi::user()->getId() ?>',
            t: {
                SEARCH: '<?php echo _e('Search on this group'); ?>',
                TITLE: '<?php echo _e('Title'); ?>',
                ALL: '<?php echo _e('All'); ?>',
                CATEGORY_LIST: '<?php echo _e('Category list'); ?>',
                CLOSE: '<?php echo _e('Close'); ?>',
                NONE_VIDEO: '<?php echo _e('No video'); ?>'
            },
        });
</script>
<script src="<?php echo $this->assetModule('js/video-list.js'); ?>"></script>