<?php
$this->css($this->assetModule('css/front.css'));
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($this->escape($videoItem['title']), 'og:title', 'property');
$this->headMeta($this->escape($videoItem['videoUrl']), 'og:url', 'property');
$this->headMeta('video', 'og:type', 'property');

if ($videoItem['server']['type'] == 'file') {
    $this->headMeta($this->escape($videoItem['videoFileUrl']), 'og:video:url', 'property');
    $this->headMeta($this->escape($videoItem['videoFileUrl']), 'og:video:secure_url', 'property');
}

if ($videoItem['video_type'] == 'video') {
    $this->headMeta('video/mp4', 'og:video:type', 'property');
} elseif ($videoItem['video_type'] == 'audio') {
    $this->headMeta('audio/mp3', 'og:video:type', 'property');
}
if (isset($videoItem['video_duration']) && !empty($videoItem['video_duration'])) {
    //$this->headMeta(_strip($videoItem['video_duration']), 'video:duration', 'property');
}
if (isset($videoItem['largeUrl']) && !empty($videoItem['largeUrl'])) {
    $this->headMeta($this->escape($videoItem['largeUrl']), 'og:image', 'property');
}
if (isset($videoItem['largeUrl']) && !empty($videoItem['largeUrl'])) {
    $this->headMeta($this->escape($videoItem['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta('player', 'twitter:card');
$this->headMeta($this->escape($videoItem['title']), 'twitter:title');
if (isset($videoItem['text_summary']) && !empty($videoItem['text_summary'])) {
    $this->headMeta(_strip($videoItem['text_summary']), 'twitter:description');
}
if (isset($videoItem['largeUrl']) && !empty($videoItem['largeUrl'])) {
    $this->headMeta($this->escape($videoItem['largeUrl']), 'twitter:image');
}

if ($access) {
    if ($videoItem['server']['type'] == 'wowza') {
        $this->jQuery();
        $this->js($this->assetModule('player/shaka/shaka-player.compiled.js'));
        $script = <<<'EOT'
    var manifestUri = '%s';

    function initApp() {
        // Install built-in polyfills to patch browser incompatibilities.
        shaka.polyfill.installAll();

        // Check to see if the browser supports the basic APIs Shaka needs.
        if (shaka.Player.isBrowserSupported()) {
            // Everything looks good!
            initPlayer();
        } else {
            // This browser does not have the minimum set of APIs we need.
            console.error('Browser not supported!');
        }
    }

    function initPlayer() {
        // Create a Player instance.
        var video = document.getElementById('video');
        var player = new shaka.Player(video);

        // Attach player to the window to make it easy to access in the JS console.
        window.player = player;
        
        // Set config
        // player.configure({});

        // Listen for error events.
        player.addEventListener('error', onErrorEvent);

        // Try to load a manifest.
        // This is an asynchronous process.
        player.load(manifestUri).then(function() {
            // This runs if the asynchronous load is successful.
            console.log('The video has now been loaded!');
        }).catch(onError);  // onError is executed if the asynchronous load fails.
    }

    function onErrorEvent(event) {
        // Extract the shaka.util.Error object from the event.
        onError(event.detail);
    }

    function onError(error) {
        // Log the error.
        console.error('Error code', error.code, 'object', error);
    }

    document.addEventListener('DOMContentLoaded', initApp);
EOT;
        $script = sprintf($script, $videoItem['mpegDashUrl']);
        $this->footScript()->appendScript($script);
        $os = Pi::service('browser')->getPlatform();
    } elseif ($videoItem['server']['type'] == 'qmery') {
        $this->jQuery();
        $this->headScript()->appendFile($videoItem['qmeryScript']);
    }
}
?>
<div class="clearfix video-page" itemscope itemtype="https://schema.org/VideoObject">
    <div class="page-header">
        <h1 itemprop="name"><?php echo $this->escape($videoItem['title']); ?></h1>
    </div>
    <meta itemprop="thumbnail" content="<?php echo $this->escape($videoItem['largeUrl']); ?>" />
    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $videoItem['time_create'])); ?>" />
    <meta itemprop="contentUrl" content="<?php echo $this->escape($videoItem['videoFileUrl']); ?>" />
    <div class="row clearfix">
        <div class="col-md-8">
            <div class="clearfix video-information">
                <ul class="text-muted list-inline small">
                    <li><i class="fa fa-calendar"></i> <?php echo $this->escape($videoItem['time_update_view']); ?></li>
                    <li><i class="fa fa-eye"></i> <?php echo _number($this->escape($videoItem['hits'])); ?></li>
                    <li><i class="fa fa-clock-o"></i> <?php echo $this->escape($videoItem['video_duration_view']); ?></li>
                    <li><i class="fa fa-folder"></i></li>
                    <?php foreach ($videoItem['categories'] as $videoCategory) { ?>
                        <li class="p-category" itemprop="about">
                            <a title="<?php echo $this->escape($videoCategory['title']); ?>" href="<?php echo $this->escape($videoCategory['url']); ?>">
                                <?php echo $this->escape($videoCategory['title']); ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <?php if ($access) { ?>
                <div class="text-center video-player">
                    <?php if ($videoItem['server']['type'] == 'file') { ?>
                        <?php echo $this->videojs($videoItem['videoFileUrl'], $videoItem['largeUrl']); ?>
                    <?php } elseif ($videoItem['server']['type'] == 'qmery') { ?>
                        <?php if (isset($videoItem['server']['qmery_player_type']) && $videoItem['server']['qmery_player_type'] == 'iframe') { ?>
                            <div class="clearfix">
                                <iframe src="<?php echo $this->escape($videoItem['qmeryDirect']); ?>" allowtransparency="true" scrolling="no" name="qmery_embed_video" allowfullscreen="" mozallowfullscreen="" webkitallowfullscreen="" oallowfullscreen="" msallowfullscreen="" frameborder="0" height="360" width="640"></iframe>
                            </div>
                        <?php } else { ?>
                            <div class="qmery-player-min-height">
                                <div class="qmery-player-full-height">
                                    <div class="qmery-player">
                                        <div id="embed_qmery_player_<?php echo $this->escape($videoItem['video_qmery_id']); ?>"></div>
                                        <div id="embed_qmery_player_icons<?php echo $this->escape($videoItem['video_qmery_id']); ?>"></div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    <?php } elseif ($videoItem['server']['type'] == 'wowza') { ?>
                        <div class="clearfix">
                            <?php if (in_array($os, array('Android', 'WindowsPhone', 'BlackBerry'))) { ?>
                                <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                    <div class="btn-group" role="group">
                                        <a href="<?php echo $this->escape($videoItem['androidUrl']); ?>" class="btn btn-success btn-lg">
                                            <i class="fa fa-play" aria-hidden="true"></i> <?php _e('Play'); ?>
                                        </a>
                                    </div>
                                </div>
                            <?php } elseif (in_array($os, array('Ios', 'iPhone', 'iPad'))) { ?>
                                <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                    <div class="btn-group" role="group">
                                        <a href="<?php echo $this->escape($videoItem['iosUrl']); ?>" class="btn btn-success btn-lg">
                                            <i class="fa fa-play" aria-hidden="true"></i> <?php _e('Play'); ?>
                                        </a>
                                    </div>
                                </div>
                            <?php } ?>
                            <div id="videoContainer" class="overlay-parent">
                                <video id="video"
                                       class="video-player"
                                       width="100%"
                                       poster="<?php echo $this->escape($videoItem['largeUrl']); ?>"
                                       controls
                                       autoplay></video>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <div class="clearfix">
                    <div class="thumbnail text-center">
                        <img class="img-responsive" src="<?php echo $this->escape($videoItem['largeUrl']); ?>" alt="<?php echo $this->escape($videoItem['title']); ?>">
                        <div class="caption">
                            <p><?php _e('This is paid video and you dont have access to watch it, use buy button to paid and watch this video'); ?></p>
                            <div class="clearfix">
                                <a target="_blank" href="<?php echo $this->escape($videoItem['payUrl']); ?>" class="btn btn-success"><?php _e('Pay and watch video'); ?></a>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="clearfix video-info-list">
                <ul class="list-inline">
                    <?php if (!empty($vote)) { ?>
                        <li class="col-md-3">
                            <?php include $this->template('votebar.phtml', 'front', 'vote'); ?>
                        </li>
                    <?php } ?>
                    <?php if (!empty($favourite)) { ?>
                        <li class="col-md-3">
                            <?php include $this->template('favouritebar.phtml', 'front', 'favourite'); ?>
                        </li>
                    <?php } ?>
                    <?php if ($config['social_sharing']) { ?>
                        <li class="col-md-6">
                            <div class="socialSharing">
                                <?php echo $this->socialSharing(
                                    $config['social_sharing'],
                                    $this->escape($videoItem['title']),
                                    $this->escape($videoItem['videoUrl']),
                                    $this->escape($videoItem['largeUrl'])
                                ); ?>
                            </div>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <div class="well well-sm clearfix">
                <h2><?php _e('Description'); ?></h2>
                <div class="clearfix video-info-box" itemprop="description">
                    <?php echo $videoItem['text_summary']; ?>
                </div>
                <div class="clearfix video-info-box" itemprop="description">
                    <?php echo $videoItem['text_description']; ?>
                </div>
            </div>
            <?php include $this->template('front/tag'); ?>
        </div>
        <div class="col-md-4">
            <!-- <div class="video-channel" itemprop="author" itemscope itemtype="https://schema.org/Person">
                <a title="<?php _e('User channel'); ?>" href="<?php echo $this->escape($videoItem['channelUrl']); ?>">
                    <?php echo $submitter['avatar']; ?>
                    <?php echo sprintf(__('%s channel'), $this->escape($submitter['name'])); ?>
                </a>
                <meta itemprop="name" content="<?php echo $this->escape($submitter['name']); ?>" />
            </div> -->
            <?php include $this->template('front/attribute'); ?>
            <?php include $this->template('front/video-related'); ?>
        </div>
    </div>
</div>