<?php if (isset($videoRelated) && !empty($videoRelated)) { ?>
    <div class="video-related">
        <h2 class="video-related-title">
            <i class="far fa-caret-square-left"></i> <?php _e('Related videos'); ?>
        </h2>
        <div class="list-group">
            <?php foreach ($videoRelated as $related) { ?>
                <div class="list-group-item">
                    <div class="clearfix row">
                    <a class="col-md-3 col-12" title="<?php echo $this->escape($related['title']); ?>" href="<?php echo $this->escape($related['videoUrl']); ?>" >
                        <img src="<?php echo $this->escape($related['thumbUrl']); ?>" alt="<?php echo $this->escape($related['title']); ?>" class="img-fluid">
                    </a>
                    <h5 class="col-md-9 col-12">
                        <a title="<?php echo $this->escape($related['title']); ?>" href="<?php echo $this->escape($related['videoUrl']); ?>">
                            <?php echo $this->escape($related['title']); ?>
                        </a>
                    </h5>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>
